Chill\ICPC2Bundle\Entity\Code:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 3
        name:
            type: json_array
    manyToOne:
        user:
            targetEntity: Chill\MainBundle\Entity\User
        chapter:
            targetEntity: Chill\ICPC2Bundle\Chapter
        component:
            targetEntity: Chill\ICPC2Bundle\Component
    lifecycleCallbacks: {  }
