services:
    chill.icp2.type:
        class: Chill\ICPC2Bundle\CustomField\CustomFieldICPC2Code
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@request_stack"
            - %locale%
            - "@templating"
            - "@chill.main.helper.translatable_string"
        tags:
            - { name: 'chill.custom_field', type: 'ICPC2' }
