<?php

/*
 * Chill is a software for social workers
 * Copyright (C) 2014, Champs Libres Cooperative SCRLFS, <http://www.champs-libres.coop>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Chill\ICPC2Bundle\Command;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Chill\CustomFieldsBundle\Entity\CustomFieldsGroup;
use Symfony\Component\Yaml\Parser;
use Symfony\Component\Yaml\Exception\ParseException;
use Chill\CustomFieldsBundle\Entity\CustomField;
use Chill\ICPC2Bundle\Entity\Chapter;
use Chill\ICPC2Bundle\Entity\Component;
use Chill\ICPC2Bundle\Entity\Code;


class DBLoadICPC2CodesCommand extends ContainerAwareCommand
{
    protected function configure()
    {
        $this
            ->setName('chill:icpc2:db:load')
            ->setDescription('Load ICPC2 Codes into the DB')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $em = $this->getContainer()->get('doctrine.orm.entity_manager');

        $output->writeln('Cleaning the DB');

        foreach (['Code', 'Component', 'Chapter'] as $entityName) {
            foreach ($em->getRepository('ChillICPC2Bundle:'.$entityName) as $c) { 
                $em->remove($c);
            }
        }

        $output->writeln('Loading Chapters');

        $chapters = $this->_loadChapter($em, $output);

        $output->writeln('Loading Components');

        $components = $this->_loadComponents($em, $output);

        $output->writeln('Loading Codes');

        $this->_loadCodes($em, $chapters, $components, $output);

        $em->flush();
    }

    private function _loadChapter(ObjectManager $em, OutputInterface $output)
    {
        $dataChapters =  [
            array("en" => "Process codes", "fr" => "Procédures", "nl"=> "Standaard procescomponenten", "slug" => "-"),
            array("en" => "General and Unspecified", "fr" => "Général et non spécifié", "nl"=> "Algemeen en niet gespecificeerd",  "slug" => "A"),
            array("en" => "Blood, Blood Forming, Organs and Immune Mechanism", "fr" => "Sang, syst. hématop/ immunol.", "nl"=> "Bloed, bloedvormende organen en immuunstelsel",  "slug" => "B"),
            array("en" => "Digestive", "fr" => "Syst. Digestif","nl"=> "Spijsverteringsorganen",  "slug" => "D"),
            array("en" => "Eye", "fr" => "Oeil", "nl"=> "Oog", "slug" => "F"),
            array("en" => "Ear", "fr" => "Oreille", "nl"=> "Oor", "slug" => "H"),
            array("en" => "Cardiovascular", "fr" => "Cardio-vasculaire", "nl"=> "Cardiovasculair stelsel", "slug" => "K"),
            array("en" => "Musculoskeletal", "fr" => "Ostéo-articulaire", "nl"=> "Bewegingsapparaat", "slug" => "L"),
            array("en" => "Neurological", "fr" => "Neurologique", "nl"=> "Zenuwstelsel", "slug" => "N"),
            array("en" => "Psychological", "fr" => "Psychologique", "nl"=> "Psychische problemen", "slug" => "P"),
            array("en" => "Respiratory", "fr" => "Respiratoire", "nl"=> "Luchtwegen", "slug" => "R"),
            array("en" => "Skin", "fr" => "Peau", "nl"=> "Huid", "slug" => "S"),
            array("en" => "Endocrine/Metabolic and Nutritional", "fr" => "Métabol., nutrit., endocrinien", "nl"=> "Endocriene klieren/ stofwisseling/ voeding", "slug" => "T"),
            array("en" => "Urological", "fr" => "Système Urinaire", "nl"=> "Urinewegen", "slug" => "U"),
            array("en" => "Pregnancy, Childbearing, Family Planning", "fr" => "Grossesse, accouchement et PF", "nl"=> "Zwangerschap, bevalling en geboorteregeling", "slug" => "W"),
            array("en" => "Female Genital", "fr" => "Syst.génital féminin et sein", "nl"=> "Vrouwel. geslachtsorganen (incl. borsten)", "slug" => "X"),
            array("en" => "Male Genital", "fr" => "Syst. génital masculin et sein", "nl"=> "Mannelijke geslachtsorganen (incl. borsten)", "slug" => "Y"),
            array("en" => "Social Problems", "fr" => "Social", "nl"=> "Sociale problemen", "slug" => "Z")
        ];

        $chapters = array();

        foreach ($dataChapters as $c) {
            $output->writeln($c["en"]);
            $e = (new Chapter())
                ->setSlug($c["slug"])
                ->setName(array("en" => $c["en"], "fr" => $c["fr"], "nl" => $c["nl"]));
            $chapters[$c["slug"]] = $e;
            $em->persist($e);
        }

        return $chapters;
    }

    private function _loadComponents(ObjectManager $em, OutputInterface $output)
    {
        $dataComponents =  [
            array("en" => "PROCESS CODES", "slug" => "pro", "fr" => "Codes procédure", "nl" => "Processcodes"),
            array("en" => "SYMPTOMS/COMPLAINTS", "slug" => "sym", "fr" => "Symptômes et plaintes", "nl" => "Symptomen/klachten"),
            array("en" => "INFECTIONS", "slug" => "inf", "fr" => "Infections", "nl" => "Infecties"),
            array("en" => "NEOPLASMS", "slug" => "neo", "fr" => "Néoplasmes", "nl" => "Neoplasmata"),
            array("en" => "INJURIES", "slug" => "inj", "fr" => "Traumatismes", "nl" => "Traumata"),
            array("en" => "CONGENITAL ANOMALIES", "slug" => "con", "fr" => "Anomalies congénitales", "nl" => "Aangeboren afwijkingen"),
            array("en" => "OTHER DIAGNOSES", "slug" => "oth", "fr" => "Autres diagnostics", "nl" => "Andere diagnosen"),
        ];

        $components = array();

        foreach ($dataComponents as $c) {
            $output->writeln($c["en"]);
            $e = (new Component())
                ->setSlug($c["slug"])
                ->setName(array("en" => $c["en"], "fr" => $c["fr"], "nl" => $c["nl"]));
            $components[$c["slug"]] = $e;
            $em->persist($e);
        }

        return $components;
    }

    private function _loadCodes(ObjectManager $em, $chapters, $components, OutputInterface $output)
    {
        $codesFR = [
["pro","-30","Ex médical/bilan santé détaillé"],
["pro","-31","Ex médical/bilan santé partiel"],
["pro","-32","Test de sensibilité"],
["pro","-33","Ex microbiologique/immunologique"],
["pro","-34","Autre analyse de sang"],
["pro","-35","Autre analyse d'urine"],
["pro","-36","Autre analyse de selles"],
["pro","-37","Cytologie/histologie"],
["pro","-38","Autre analyse de laboratoire"],
["pro","-39","Epreuve fonctionnelle"],
["pro","-40","Endoscopie"],
["pro","-41","Radiologie diagnostique/imagerie"],
["pro","-42","Tracé électrique"],
["pro","-43","Autre procédure diagnostique"],
["pro","-44","Vaccination/médication préventive"],
["pro","-45","Recom./éducation santé/avis/régime"],
["pro","-46","Discussion entre dispensateurs SSP"],
["pro","-47","Discussion dispensateur spécialiste"],
["pro","-48","Clarification de la demande du patient"],
["pro","-49","Autre procédure préventive"],
["pro","-50","Médication/prescription/injection"],
["pro","-51","Incision/drainage/aspiration"],
["pro","-52","Excision/biopsie/cautér/débridation"],
["pro","-53","Perfusion/intubat./dilatat./appareillage"],
["pro","-54","Répar/fixation/suture/plâtre/prothèse"],
["pro","-55","Traitement local/infiltration"],
["pro","-56","Pansement/compression/bandage"],
["pro","-57","Thérapie manuelle/médecine physique"],
["pro","-58","Conseil thérap/écoute/examens"],
["pro","-59","Autres procédures thérapeutiques"],
["pro","-60","Résultats analyses/examens"],
["pro","-61","Résultats ex/procéd autre dispensateur"],
["pro","-62","Contact administratif"],
["pro","-63","Rencontre de suivi"],
["pro","-64","Epis. nouveau/en cours init. par disp."],
["pro","-65","Epis. nouveau/en cours init. par tiers"],
["pro","-66","Référence à dispens. SSP non médecin"],
["pro","-67","Référence à médecin"],
["pro","-68","Autre référence"],
["pro","-69","Autres procédures"],
["sym","A01","Douleur générale/de sites multiples"],
["sym","A02","Frissons"],
["sym","A03","Fièvre"],
["sym","A04","Fatigue/faiblesse générale"],
["sym","A05","Sensation d'être malade"],
["sym","A06","Evanouissement/syncope"],
["sym","A07","Coma"],
["sym","A08","Gonflement"],
["sym","A09","P. de transpiration"],
["sym","A10","Saignement/hémorragie NCA"],
["sym","A11","Douleur thoracique NCA"],
["sym","A13","Préoc. par/peur traitement médical"],
["sym","A16","Nourrisson irritable"],
["sym","A18","Préoc. par son aspect extérieur"],
["sym","A20","Demande/discussion sur l'euthanasie"],
["sym","A21","Facteur de risque de cancer"],
["sym","A23","Facteur de risque NCA"],
["sym","A25","Peur de la mort, de mourir"],
["sym","A26","Peur du cancer NCA"],
["sym","A27","Peur d'une autre maladie NCA"],
["sym","A28","Limitation de la fonction/incap. NCA"],
["sym","A29","Autre S/P général"],
["inf","A70","Tuberculose"],
["inf","A71","Rougeole"],
["inf","A72","Varicelle"],
["inf","A73","Paludisme"],
["inf","A74","Rubéole"],
["inf","A75","Mononucléose infectieuse"],
["inf","A76","Autre exanthème viral"],
["inf","A77","autre maladie virale NCA"],
["inf","A78","Autre maladie infectieuse NCA"],
["neo","A79","Cancer NCA"],
["inj","A80","Traumatisme/lésion traumat. NCA"],
["inj","A81","Polytraumatisme/lésions multiples"],
["inj","A82","Effet tardif d'un traumatisme"],
["inj","A84","Intoxication par subst. médicinale"],
["inj","A85","Effet sec. subst. médicinale"],
["inj","A86","Effet toxique subst. non médicinale"],
["inj","A87","Complication de traitement médical"],
["inj","A88","Effet sec. de facteur physique"],
["inj","A89","Effet sec. de matériel prothétique"],
["con","A90","Anom. congénitale NCA/multiple"],
["oth","A91","Résultat d'investigat. anormale NCA"],
["oth","A92","Allergie/réaction allergique NCA"],
["oth","A93","Nouveau-né prématuré"],
["oth","A94","Autre morbidité périnatale"],
["oth","A95","Mortalité périnatale"],
["oth","A96","Mort"],
["oth","A97","Pas de maladie"],
["oth","A98","Gestion santé/médecine préventive"],
["oth","A99","Maladie de nature/site non précisé"],
["sym","B02","Ganglion lymph. augmenté/ douloureux"],
["sym","B04","S/P du sang"],
["sym","B25","Peur du SIDA/du VIH"],
["sym","B26","Peur du cancer du sang/lymph."],
["sym","B27","Peur autre maladie sang/lymph/rate"],
["sym","B28","Limitation de la fonction/incap. (B)"],
["sym","B29","Autre S/P du syst. lymph./immunol."],
["inf","B70","Adénite aiguë"],
["inf","B71","Adénite chronique/non-spécifique"],
["neo","B72","Maladie de Hodgkin/lymphome"],
["neo","B73","Leucémie"],
["neo","B74","Autre cancer du sang"],
["neo","B75","Tumeur bénigne/indét. sang/lymph."],
["inj","B76","Rupture traumat. de la rate"],
["inj","B77","Autre traumat. sang/lymph/rate"],
["con","B78","Anémie hémolytique héréditaire"],
["con","B79","Autre anom. congénitale sang/ lymph/rate"],
["oth","B80","Anémie par déficience en fer"],
["oth","B81","Anémie carence vit B12/ac. folique"],
["oth","B82","Autre anémie/indét."],
["oth","B83","Purpura/défaut de coagulation"],
["oth","B84","Globules blancs anormaux"],
["oth","B87","Splénomégalie"],
["oth","B90","Infection par le virus HIV, SIDA"],
["oth","B99","Autre maladie sang/lymph/rate"],
["sym","D01","Douleur/crampes abdominales gén."],
["sym","D02","Douleur abdominale/épigastrique"],
["sym","D03","Brûlure/brûlant/brûlement estomac"],
["sym","D04","Douleur rectale/anale"],
["sym","D05","Démangeaisons périanales"],
["sym","D06","Autre douleur abdominale loc."],
["sym","D07","Dyspepsie/indigestion"],
["sym","D08","Flatulence/gaz/renvoi"],
["sym","D09","Nausée"],
["sym","D10","Vomissement"],
["sym","D11","Diarrhée"],
["sym","D12","Constipation"],
["sym","D13","Jaunisse"],
["sym","D14","Hématémèse/vomissement de sang"],
["sym","D15","Méléna"],
["sym","D16","Saignement rectal"],
["sym","D17","Incontinence rectale"],
["sym","D18","Modification selles/mouvem. intestin"],
["sym","D19","S/P dents/gencives"],
["sym","D20","S/P bouche/langue/lèvres"],
["sym","D21","P. de déglutition"],
["sym","D23","Hépatomégalie"],
["sym","D24","Masse abdominale NCA"],
["sym","D25","Distension abdominale"],
["sym","D26","Peur du cancer du syst. digestif"],
["sym","D27","Peur d’une autre maladie digestive"],
["sym","D28","Limitation de la fonction/incap. (D)"],
["sym","D29","Autre S/P du syst. digestif"],
["inf","D70","Infection gastro-intestinale"],
["inf","D71","Oreillons"],
["inf","D72","Hépatite virale"],
["inf","D73","Gastro-entérite présumée infectieuse"],
["neo","D74","Cancer de l'estomac"],
["neo","D75","Cancer du colon/du rectum"],
["neo","D76","Cancer du pancréas"],
["neo","D77","Autre cancer digestif/NCA"],
["neo","D78","Tumeur bénigne/indét. du syst. dig."],
["inj","D79","CE du syst. digestif"],
["inj","D80","Autre traumat. du syst. digestif"],
["con","D81","Anom. congénitale du syst. digestif"],
["oth","D82","Maladie des dents/des gencives"],
["oth","D83","Maladie bouche/langue/lèvres"],
["oth","D84","Maladie de l’œsophage"],
["oth","D85","Ulcère duodénal"],
["oth","D86","Autre ulcère peptique"],
["oth","D87","Trouble de la fonction gastrique"],
["oth","D88","Appendicite"],
["oth","D89","Hernie inguinale"],
["oth","D90","Hernie hiatale"],
["oth","D91","Autre hernie abdominale"],
["oth","D92","Maladie diverticulaire"],
["oth","D93","Syndrome du colon irritable"],
["oth","D94","Entérite chronique/colite ulcéreuse"],
["oth","D95","Fissure anale/abcès périanal"],
["oth","D96","Vers/autre parasite"],
["oth","D97","Maladie du foie NCA"],
["oth","D98","Cholécystite/cholélithiase"],
["oth","D99","Autre maladie du syst. Digestif"],
["sym","F01","Oeil douloureux"],
["sym","F02","Oeil rouge"],
["sym","F03","Ecoulement de l’œil"],
["sym","F04","Taches visuelles/flottantes"],
["sym","F05","Autre perturbation de la vision"],
["sym","F13","Sensation oculaire anormale"],
["sym","F14","Mouvements oculaires anormaux"],
["sym","F15","Apparence anormale de l’œil"],
["sym","F16","S/P de la paupière"],
["sym","F17","S/P lunettes"],
["sym","F18","S/P lentilles de contact"],
["sym","F27","Peur d’une maladie de l’œil"],
["sym","F28","Limitation de la fonction/incap. (F)"],
["sym","F29","Autre S/P de l’œil"],
["inf","F70","Conjonctivite infectieuse"],
["inf","F71","Conjonctivite allergique"],
["inf","F72","Blépharite, orgelet, chalazion"],
["inf","F73","Autre infection/inflammation de l’œil"],
["neo","F74","Tumeur de l’œil et des annexes"],
["inj","F75","Contusion/hémorragie de l’œil"],
["inj","F76","CE dans l’œil"],
["inj","F79","Autre lésion traumat. de l’œil"],
["con","F80","Sténose canal lacrymal de l'enfant"],
["con","F81","Autre anom. congénitale de l’œil"],
["oth","F82","Décollement de la retire"],
["oth","F83","Rétinopathie"],
["oth","F84","Dégénérescence maculaire"],
["oth","F85","Ulcère de la cornée"],
["oth","F86","Trachome"],
["oth","F91","Défaut de réfraction"],
["oth","F92","Cataracte"],
["oth","F93","Glaucome"],
["oth","F94","Cécité"],
["oth","F95","Strabisme"],
["oth","F99","Autre maladie de l’œil/annexes"],
["sym","H01","Douleur d'oreille/otalgie"],
["sym","H02","P. d'audition"],
["sym","H03","Acouphène/bourdonnement d'oreille"],
["sym","H04","Ecoulement de l'oreille"],
["sym","H05","Saignement de l'oreille"],
["sym","H13","Sensation d'oreille bouchée"],
["sym","H15","Préoc. par l'aspect des oreilles"],
["sym","H27","Peur d’une maladie de l'oreille"],
["sym","H28","Limitation de la fonction/incap. (H)"],
["sym","H29","Autre S/P de l' oreille"],
["inf","H70","Otite externe"],
["inf","H71","Otite moyenne aiguë/myringite"],
["inf","H72","Otite moyenne séreuse"],
["inf","H73","Salpingite d'eustache"],
["inf","H74","Otite moyenne chronique"],
["neo","H75","Tumeur de l'oreille"],
["inj","H76","CE dans l'oreille"],
["inj","H77","Perforation du tympan"],
["inj","H78","Lésion traumat. superf. de l'oreille"],
["inj","H79","Autre lésion traumat. de l'oreille"],
["con","H80","Anom. congénitale de l'oreille"],
["oth","H81","Excès de cérumen"],
["oth","H82","Syndrome vertigineux"],
["oth","H83","Otosclérose"],
["oth","H84","Presbyacousie"],
["oth","H85","Traumatisme sonore"],
["oth","H86","Surdité"],
["oth","H99","Autre maladie de l'oreille/ mastoïde"],
["sym","K01","Douleur cardiaque"],
["sym","K02","Oppression/constriction cardiaque"],
["sym","K03","Douleur cardiovasculaire NCA"],
["sym","K04","Palpitat./perception battements card."],
["sym","K05","Autre battement cardiaque irrégulier"],
["sym","K06","Veines proéminentes"],
["sym","K07","Oedème, gonflement des chevilles"],
["sym","K22","Facteur risque mal. cardio-vasculaire"],
["sym","K24","Peur d’une maladie de cœur"],
["sym","K25","Peur d' de l'hypertension"],
["sym","K27","Peur autre maladie cardio-vasculaire"],
["sym","K28","Limitation de la fonction/incap. (K)"],
["sym","K29","Autre S/P cardiovasculaire"],
["inf","K70","Infection du syst. cardio-vasculaire"],
["inf","K71","RAA/maladie cardiaque rhumatismale"],
["neo","K72","Tumeur cardio-vasculaire"],
["con","K73","Anom. congénitale cardio-vasculaire"],
["oth","K74","Cardiopathie ischémique avec angor"],
["oth","K75","Infarctus myocardique aigu"],
["oth","K76","Cardiopathie ischémique sans angor"],
["oth","K77","Décompensation cardiaque"],
["oth","K78","Fibrillation auriculaire/flutter"],
["oth","K79","Tachycardie paroxystique"],
["oth","K80","Arythmie cardiaque NCA"],
["oth","K81","Souffle cardiaque/artériel NCA"],
["oth","K82","Cœur pulmonaire"],
["oth","K83","Valvulopathie NCA"],
["oth","K84","Autre maladie cardiaque"],
["oth","K85","Pression sanguine élevée"],
["oth","K86","Hypertension non compliquée"],
["oth","K87","Hypertension avec complication"],
["oth","K88","Hypotension orthostatique"],
["oth","K89","Ischémie cérébrale transitoire"],
["oth","K90","Accident vasculaire cérébral"],
["oth","K91","Maladie cérébrovasculaire"],
["oth","K92","Athéroscl./mal. vasculaire périphér."],
["oth","K93","Embolie pulmonaire"],
["oth","K94","Phlébite et thrombophlébite"],
["oth","K95","Varices des jambes"],
["oth","K96","Hémorroïdes"],
["oth","K99","Autre maladie cardio-vasculaire"],
["sym","L01","S/P du cou"],
["sym","L02","S/P du dos"],
["sym","L03","S/P des lombes"],
["sym","L04","S/P du thorax"],
["sym","L05","S/P du flanc et du creux axillaire"],
["sym","L07","S/P de la mâchoire"],
["sym","L08","S/P de l'épaule"],
["sym","L09","S/P du bras"],
["sym","L10","S/P du coude"],
["sym","L11","S/P du poignet"],
["sym","L12","S/P de la main et du doigt"],
["sym","L13","S/P de la hanche"],
["sym","L14","S/P de la jambe et de la cuisse"],
["sym","L15","S/P du genou"],
["sym","L16","S/P de la cheville"],
["sym","L17","S/P du pied et de l'orteil"],
["sym","L18","Douleur musculaire"],
["sym","L19","S/P musculaire NCA"],
["sym","L20","S/P d'une articulation NCA"],
["sym","L26","Peur cancer syst. ostéo-articulaire"],
["sym","L27","Peur autre maladie syst. ostéo-articul."],
["sym","L28","Limitation de la fonction/incap. (L)"],
["sym","L29","Autre S/P ostéo-articulaire"],
["inf","L70","Infection du syst. ostéo-articulaire"],
["neo","L71","Cancer du syst. ostéo-articulaire"],
["inj","L72","Fracture du radius/du cubitus"],
["inj","L73","Fracture du tibia/du péroné"],
["inj","L74","Fracture de la main/du pied"],
["inj","L75","Fracture du fémur"],
["inj","L76","Autre fracture"],
["inj","L77","Entorse de la cheville"],
["inj","L78","Entorse du genou"],
["inj","L79","Entorse articulaire NCA"],
["inj","L80","Luxation et subluxation"],
["inj","L81","Lésion traumat. NCA ostéo-articulaire"],
["con","L82","Anom. congénitale ostéo-articulaire"],
["oth","L83","Syndrome cervical"],
["oth","L84","Syndr. dorso-lomb. sans irradiation"],
["oth","L85","Déformation acquise de la colonne"],
["oth","L86","Syndr. dorso-lombaire et irradiation"],
["oth","L87","Bursite, tendinite, synovite NCA"],
["oth","L88","Polyarthrite rhumatoïde séropositive"],
["oth","L89","Coxarthrose"],
["oth","L90","Gonarthrose"],
["oth","L91","Autre arthrose"],
["oth","L92","Syndrome de l'épaule"],
["oth","L93","Coude du joueur de tennis"],
["oth","L94","Ostéochondrose"],
["oth","L95","Ostéoporose"],
["inj","L96","Lésion aiguë interne du genou"],
["neo","L97","Autre tumeur bén./indét. ostéo-artic."],
["oth","L98","Déformation acquise membres inf."],
["oth","L99","Autre maladie ostéo-articulaire"],
["sym","N01","Mal de tête"],
["sym","N03","Douleur de la face"],
["sym","N04","Jambes sans repos"],
["sym","N05","Fourmillements doigts, pieds, orteils"],
["sym","N06","Autre perturbation de la sensibilité"],
["sym","N07","Convulsion/crise comitiale"],
["sym","N08","Mouvements involontaires anormaux"],
["sym","N16","Perturbation du goût/de l'odorat"],
["sym","N17","Vertige/étourdissement"],
["sym","N18","Paralysie/faiblesse"],
["sym","N19","Trouble de la parole"],
["sym","N26","Peur d'un cancer neurologique"],
["sym","N27","Peur d’une autre maladie neurologique"],
["sym","N28","Limitation de la fonction/incap. (N)"],
["sym","N29","Autre S/P neurologique"],
["inf","N70","Poliomyélite"],
["inf","N71","Méningite/encéphalite NCA"],
["inf","N72","Tétanos"],
["inf","N73","Autre infection neurologique"],
["neo","N74","Cancer du syst. neurologique"],
["neo","N75","Tumeur bénigne neurologique"],
["neo","N76","Autre tumeur indét. neurologique"],
["inj","N79","Commotion"],
["inj","N80","Autre lésion traumat. de la tête"],
["inj","N81","Autre lésion traumat. neurologique"],
["con","N85","Anom. congénitale neurologique"],
["oth","N86","Sclérose en plaque"],
["oth","N87","Syndrome parkinsonien"],
["oth","N88","Epilepsie"],
["oth","N89","Migraine"],
["oth","N90","Algie vasculaire de la face"],
["oth","N91","Paralysie faciale/paralysie de Bell"],
["oth","N92","Névralgie du trijumeau"],
["oth","N93","Syndrome du canal carpien"],
["oth","N94","Névrite/neuropathie périphérique"],
["oth","N95","Céphalée de tension"],
["oth","N99","Autre maladie neurologique"],
["sym","P01","Sensation anxiété/nervosité/tension"],
["sym","P02","Réaction de stress aiguë"],
["sym","P03","Sensation de dépression"],
["sym","P04","Sentiment/comport. irritable/colère"],
["sym","P05","Sensation vieux, comportement sénile"],
["sym","P06","Perturbation du sommeil"],
["sym","P07","Diminution du désir sexuel"],
["sym","P08","Diminution accomplissement sexuel"],
["sym","P09","Préoccupation sur identité sexuelle"],
["sym","P10","Bégaiement, bredouillement, tic"],
["sym","P11","Trouble de l'alimentation de l'enfant"],
["sym","P12","Enurésie"],
["sym","P13","Encoprésie"],
["sym","P15","Alcoolisme chronique"],
["sym","P16","Alcoolisation aiguë"],
["sym","P17","Usage abusif du tabac"],
["sym","P18","Usage abusif de médicament"],
["sym","P19","Usage abusif de drogue"],
["sym","P20","Perturbation de la mémoire"],
["sym","P22","S/P du comportement de l'enfant"],
["sym","P23","S/P du comportement de l'adolescent"],
["sym","P24","P. spécifique de l'apprentissage"],
["sym","P25","Problèmes de phase de vie adulte"],
["sym","P27","Peur d'un trouble mental"],
["sym","P28","Limitation de la fonction/incap. (P)"],
["sym","P29","Autre S/P psychologique"],
["oth","P70","Démence"],
["oth","P71","Autre psychose organique"],
["oth","P72","Schizophrénie"],
["oth","P73","Psychose affective"],
["oth","P74","Trouble anxieux/état anxieux"],
["oth","P75","Trouble somatoforme"],
["oth","P76","Dépression"],
["oth","P77","Suicide/tentative de suicide"],
["oth","P78","Neurasthénie, surmenage"],
["oth","P79","Phobie, trouble obsessionnel compulsif"],
["oth","P80","Trouble de la personnalité"],
["oth","P81","Trouble hyperkinétique"],
["oth","P82","Syndrome de stress post-traumatique"],
["oth","P85","Retard mental"],
["oth","P86","Anorexie mentale, boulimie"],
["oth","P98","Autre psychose NCA"],
["oth","P99","Autre trouble psychologique"],
["sym","R01","Douleur du syst. respiratoire"],
["sym","R02","Souffle court, dyspnée"],
["sym","R03","Sibilance"],
["sym","R04","Autre P. respiratoire"],
["sym","R05","Toux"],
["sym","R06","Saignement de nez, épistaxis"],
["sym","R07","Congestion nasale, éternuement"],
["sym","R08","Autre S/P du nez"],
["sym","R09","S/P des sinus"],
["sym","R21","S/P de la gorge"],
["sym","R23","S/P de la voix"],
["sym","R24","Hémoptysie"],
["sym","R25","Expectoration/glaire anormale"],
["sym","R26","Peur d'un cancer du syst. respiratoire"],
["sym","R27","Peur d’une autre maladie respiratoire"],
["sym","R28","Limitation de la fonction/incap. ( R)"],
["sym","R29","Autre S/P respiratoire"],
["inf","R71","Coqueluche"],
["inf","R72","Streptococcie pharyngée"],
["inf","R73","Furoncle/abcès du nez"],
["inf","R74","Infection aiguë voies respiratoire sup."],
["inf","R75","Sinusite aiguë/chronique"],
["inf","R76","Angine aiguë"],
["inf","R77","Laryngite, trachéite aiguë"],
["inf","R78","Bronchite aiguë, bronchiolite"],
["inf","R79","Bronchite chronique"],
["inf","R80","Grippe"],
["inf","R81","Pneumonie"],
["inf","R82","Pleurésie, épanchement pleural"],
["inf","R83","Autre infection respiratoire"],
["neo","R84","Cancer des bronches, du poumon"],
["neo","R85","Autre cancer respiratoire"],
["neo","R86","Tumeur respiratoire bénigne"],
["inj","R87","CE du nez, du larynx, des bronches"],
["inj","R88","Autre lésion traumat. du syst. resp."],
["con","R89","Anom. congénitale du syst. resp."],
["oth","R90","Hypertrophie amygdales/végétations"],
["neo","R92","Autre tumeur indét. du syst. resp."],
["oth","R95","Mal. pulmonaire chronique obstructive"],
["oth","R96","Asthme"],
["oth","R97","Rhinite allergique"],
["oth","R98","Syndrome d'hyperventilation"],
["oth","R99","Autre maladie respiratoire"],
["sym","S01","Douleur/hypersensibilité de la peau"],
["sym","S02","Prurit"],
["inf","S03","Verrue"],
["sym","S04","Tuméfaction/gonflement loc. peau"],
["sym","S05","Tuméfactions/gonflements gén. peau"],
["sym","S06","Eruption localisée"],
["sym","S07","Eruption généralisée"],
["sym","S08","Modification de la couleur de la peau"],
["inf","S09","Doigt/orteil infecté"],
["inf","S10","Furoncle/anthrax"],
["inf","S11","Infection post-traumat. de la peau"],
["inj","S12","Piqûre d'insecte"],
["inj","S13","Morsure animale/humaine"],
["inj","S14","Brûlure cutanée"],
["inj","S15","CE dans la peau"],
["inj","S16","Ecchymose/contusion"],
["inj","S17","Eraflure, égratignure, ampoule"],
["inj","S18","Coupure/lacération"],
["inj","S19","Autre lésion traumat. de la peau"],
["sym","S20","Cor/callosité"],
["sym","S21","S/P au sujet de la texture de la peau"],
["sym","S22","S/P de l'ongle"],
["sym","S23","Calvitie/perte de cheveux"],
["sym","S24","Autre S/P cheveux, poils/cuir chevelu"],
["sym","S26","Peur du cancer de la peau"],
["sym","S27","Peur d’une autre maladie de la peau"],
["sym","S28","Limitation de la fonction/incap. (S)"],
["sym","S29","Autre S/P de la peau"],
["inf","S70","Zona"],
["inf","S71","Herpes simplex"],
["inf","S72","Gale/autre acariose"],
["inf","S73","Pédiculose/autre infestation peau"],
["inf","S74","Dermatophytose"],
["inf","S75","Moniliase/candidose de la peau"],
["inf","S76","Autre maladie infectieuse de la peau"],
["neo","S77","Cancer de la peau"],
["neo","S78","Lipome"],
["neo","S79","Autre tumeur bén./indét. de la peau"],
["neo","S80","Kératose actinique/coup de soleil"],
["con","S81","Hémangiome/lymphangiome"],
["con","S82","Naevus/naevus pigmentaire"],
["con","S83","Autre anom. congénitale de la peau"],
["inf","S84","Impétigo"],
["oth","S85","Kyste/fistule pilonidal"],
["oth","S86","Dermatite séborrhéique"],
["oth","S87","Dermatite atopique/eczéma"],
["oth","S88","Dermatite et allergie de contact"],
["oth","S89","Erythème fessier"],
["oth","S90","Pytiriasis rosé"],
["oth","S91","Psoriasis"],
["oth","S92","Maladie des glandes sudoripares"],
["oth","S93","Kyste sébacé"],
["oth","S94","Ongle incarné"],
["inf","S95","Molluscum contagiosum"],
["oth","S96","Acné"],
["oth","S97","Ulcère chronique de la peau"],
["oth","S98","Urticaire"],
["oth","S99","Autre maladie de la peau"],
["sym","T01","Soif excessive"],
["sym","T02","Appétit excessif"],
["sym","T03","Perte d'appétit"],
["sym","T04","P. d'alimentation nourrisson/enfant"],
["sym","T05","P. d'alimentation de l'adulte"],
["sym","T07","Gain de poids"],
["sym","T08","Perte de poids"],
["sym","T10","Retard de croissance"],
["sym","T11","Déshydratation"],
["sym","T26","Peur d'un cancer du syst. endocrinien"],
["sym","T27","Peur autre mal. endoc/métab./nutrit."],
["sym","T28","Limitation de la fonction/incap. (T)"],
["sym","T29","Autre S/P endoc/métab./nutrit.,"],
["inf","T70","Infection du syst. endocrinien"],
["neo","T71","Cancer de la thyroïde"],
["neo","T72","Tumeur bénigne de la thyroïde"],
["neo","T73","Tumeur indét. du syst. endocrinien"],
["con","T78","Canal/kyste thyréoglosse"],
["con","T80","Anom. congénit. endoc/ métab./nutrit."],
["oth","T81","Goitre"],
["oth","T82","Obésité"],
["oth","T83","Excès pondéral"],
["oth","T85","Hyperthyroïdie/thyréotoxicose"],
["oth","T86","Hypothyroïdie/myxœdème"],
["oth","T87","Hypoglycémie"],
["oth","T89","Diabète insulino-dépendant"],
["oth","T90","Diabète non insulino-dépendant"],
["oth","T91","Carence vitaminique/nutritionnelle"],
["oth","T92","Goutte"],
["oth","T93","Trouble du métabolisme des lipides"],
["oth","T99","Autre maladie endoc/métab./nutrit"],
["sym","U01","Dysurie/miction douloureuse"],
["sym","U02","Miction fréquente/impérieuse"],
["sym","U04","Incontinence urinaire"],
["sym","U05","Autre P. de miction"],
["sym","U06","Hématurie"],
["sym","U07","Autre S/P au sujet de l'urine"],
["sym","U08","Rétention d'urine"],
["sym","U13","Autre S/P de la vessie"],
["sym","U14","S/P du rein"],
["sym","U26","Peur d'un cancer du syst. urinaire"],
["sym","U27","Peur d’une autre maladie urinaire"],
["sym","U28","Limitation de la fonction/incap. (U)"],
["sym","U29","Autre S/P urinaire"],
["inf","U70","Pyélonéphrite/pyélite"],
["inf","U71","Cystite/autre infection urinaire"],
["inf","U72","Urétrite"],
["neo","U75","Cancer du rein"],
["neo","U76","Cancer de la vessie"],
["neo","U77","Autre cancer urinaire"],
["neo","U78","Tumeur bénigne du tractus urinaire"],
["neo","U79","Autre tumeur indét. urinaire"],
["inj","U80","Lésion traumat. du tractus urinaire"],
["con","U85","Anom. congénitale du tractus urinaire"],
["oth","U88","Glomérulonéph./syndr. néphrotique"],
["oth","U90","Protéinurie orthostatique"],
["oth","U95","Lithiase urinaire"],
["oth","U98","Analyse urinaire anormale NCA"],
["oth","U99","Autre maladie urinaire"],
["sym","W01","Question de grossesse"],
["sym","W02","Peur d'être enceinte"],
["sym","W03","Saignement pendant la grossesse"],
["sym","W05","Nausée/vomissement de grossesse"],
["sym","W10","Contraception post-coïtale"],
["sym","W11","Contraception orale"],
["sym","W12","Contraception intra-utérine"],
["sym","W13","Stérilisation chez la femme"],
["sym","W14","Autre contraception chez la femme"],
["sym","W15","Stérilité - hypofertilité de la femme"],
["sym","W17","Saignement du post-partum"],
["sym","W18","Autre S/P du post-partum"],
["sym","W19","S/P du sein/lactation post-partum"],
["sym","W21","Préoc. par modific. image et grossesse"],
["sym","W27","Peur complications de la grossesse"],
["sym","W28","Limitation de la fonction/incap. (W)"],
["sym","W29","Autre S/P de la grossesse"],
["inf","W70","Infection puerpérale, sepsis"],
["inf","W71","Infection compliquant la grossesse"],
["neo","W72","Tumeur maligne avec grossesse"],
["neo","W73","Tumeur bénigne/indét. et grossesse"],
["inj","W75","Lésion traumat. et grossesse"],
["con","W76","Anom. congénitale et grossesse"],
["oth","W78","Grossesse"],
["oth","W79","Grossesse non désirée"],
["oth","W80","Grossesse ectopique"],
["oth","W81","Toxémie gravidique"],
["oth","W82","Avortement spontané"],
["oth","W83","Avortement provoque"],
["oth","W84","Grossesse a haut risque"],
["oth","W85","Diabète gravidique"],
["oth","W90","Acc. non complique, enfant vivant"],
["oth","W91","Acc. non complique, enfant mort"],
["oth","W92","Acc. complique, enfant vivant"],
["oth","W93","Acc. complique, enfant mort"],
["oth","W94","Mastite puerpérale"],
["oth","W95","Autre mal. sein et grossesse/lactation"],
["oth","W96","Autre complication puerpérale"],
["oth","W99","Autre maladie de la grossesse/acc."],
["sym","X01","Douleur génitale chez la femme"],
["sym","X02","Douleur menstruelle"],
["sym","X03","Douleur intermenstruelle"],
["sym","X04","Rapport sexuel douloureux femme"],
["sym","X05","Menstruation absente/rare"],
["sym","X06","Menstruation excessive"],
["sym","X07","Menstruation irrégulière/fréquente"],
["sym","X08","Saignement intermenstruel"],
["sym","X09","S/P prémenstruel"],
["sym","X10","Ajournement des menstruations"],
["sym","X11","S/P liés a la ménopause"],
["sym","X12","Saignement de la post-ménopause"],
["sym","X13","Saignement post-coïtal femme"],
["sym","X14","Ecoulement vaginal"],
["sym","X15","S/P du vagin"],
["sym","X16","S/P de la vulve"],
["sym","X17","S/P du petit bassin chez la femme"],
["sym","X18","Douleur du sein chez la femme"],
["sym","X19","Tuméfaction/masse du sein femme"],
["sym","X20","S/P du mamelon chez la femme"],
["sym","X21","Autre S/P du sein chez la femme"],
["sym","X22","Préoc. par l'apparence des seins"],
["sym","X23","Peur d'une MST chez la femme"],
["sym","X24","Peur dysfonction sexuelle femme"],
["sym","X25","Peur d'un cancer génital femme"],
["sym","X26","Peur d'un cancer du sein femme"],
["sym","X27","Peur autre mal. génitale/sein femme"],
["sym","X28","Limitation de la fonction/incap. (X)"],
["sym","X29","Autre S/P génital chez la femme"],
["inf","X70","Syphilis chez la femme"],
["inf","X71","Gonococcie chez la femme"],
["inf","X72","Candidose génitale chez la femme"],
["inf","X73","Trichomonase génitale femme"],
["inf","X74","Mal. inflammatoire pelvienne femme"],
["neo","X75","Cancer du col de l'utérus"],
["neo","X76","Cancer du sein chez la femme"],
["neo","X77","Autre cancer génital chez la femme"],
["neo","X78","Fibrome utérin"],
["neo","X79","Tumeur bénigne du sein femme"],
["neo","X80","Tumeur bénigne génitale femme"],
["neo","X81","Autre tumeur génitale indét. femme"],
["inj","X82","Lésion traumat. génitale femme"],
["con","X83","Anom. génitale congénitale femme"],
["oth","X84","Vaginite/vulvite NCA"],
["oth","X85","Maladie du col de l'utérus NCA"],
["oth","X86","Frottis de col anormal"],
["oth","X87","Prolapsus utero-vaginal"],
["oth","X88","Maladie fibrokystique du sein"],
["oth","X89","Syndrome de tension prémenstruelle"],
["inf","X90","Herpes génital chez la femme"],
["inf","X91","Condylome acuminé chez la femme"],
["inf","X92","Infection génitale  chlamydia femme"],
["oth","X99","Autre maladie génitale de la femme"],
["sym","Y01","Douleur du pénis"],
["sym","Y02","Douleur des testicules, du scrotum"],
["sym","Y03","Ecoulement urétral chez l'homme"],
["sym","Y04","Autre S/P du pénis"],
["sym","Y05","Autre S/P des testicules/du scrotum"],
["sym","Y06","S/P de la prostate"],
["sym","Y07","Impuissance sexuelle NCA"],
["sym","Y08","Autre S/P fonction sexuelle homme"],
["sym","Y10","Stérilité, hypofertilité de l'homme"],
["sym","Y13","Stérilisation de l'homme"],
["sym","Y14","Autre PF chez l'homme"],
["sym","Y16","S/P du sein chez l'homme"],
["sym","Y24","Peur dysfonction sexuelle homme"],
["sym","Y25","Peur d’une MST chez l'homme"],
["sym","Y26","Peur d'un cancer génital homme"],
["sym","Y27","Peur autre maladie génitale homme"],
["sym","Y28","Limitation de la fonction/incap. (Y)"],
["sym","Y29","Autre S/P génitale chez l'homme"],
["inf","Y70","Syphilis chez l'homme"],
["inf","Y71","Gonococcie chez l'homme"],
["inf","Y72","Herpes génital chez l'homme"],
["inf","Y73","Prostatite/vésiculite séminale"],
["inf","Y74","Orchite/épididymite"],
["inf","Y75","Balanite"],
["inf","Y76","Condylome acuminé chez l'homme"],
["neo","Y77","Cancer de la prostate"],
["neo","Y78","Autre cancer génital chez l'homme"],
["neo","Y79","Autre tum. génit. bén./indét. homme"],
["inj","Y80","Lésion traumat. génitale homme"],
["con","Y81","Phimosis/hypertrophie du prépuce"],
["con","Y82","Hypospadias"],
["con","Y83","Ectopie testiculaire"],
["con","Y84","Autre anom. congénitale homme"],
["oth","Y85","Hypertrophie bénigne de la prostate"],
["oth","Y86","Hydrocèle"],
["oth","Y99","Autre maladie génitale chez l'homme"],
["sym","Z01","Pauvreté/P. économique"],
["sym","Z02","P. d'eau/de nourriture"],
["sym","Z03","P. d'habitat/de voisinage"],
["sym","Z04","P. socioculturel"],
["sym","Z05","P. de travail"],
["sym","Z06","P. de non emploi"],
["sym","Z07","P. d'éducation"],
["sym","Z08","P. de protection sociale"],
["sym","Z09","P. légal"],
["sym","Z10","P. relatif au syst. de soins de santé"],
["sym","Z11","P. du fait d'être malade/compliance"],
["sym","Z12","P. de relation entre partenaires"],
["sym","Z13","P. de comportement du partenaire"],
["sym","Z14","P. du à la maladie du partenaire"],
["sym","Z15","Perte/décès du partenaire"],
["sym","Z16","P. de relation avec un enfant"],
["sym","Z18","P. du à la maladie d'un enfant"],
["sym","Z19","Perte/décès d'un enfant"],
["sym","Z20","P. relation autre parent/famille"],
["sym","Z21","P. comportem. autre parent/famille"],
["sym","Z22","P. du à la mal. autre parent/famille"],
["sym","Z23","Perte/décès autre parent/famille"],
["sym","Z24","P. de relation avec un ami"],
["sym","Z25","Agression/évènement nocif NCA"],
["sym","Z27","Peur d'un P. social"],
["sym","Z28","Limitation de la fonction/incap. (Z)"],
["sym","Z29","P. social NCA"]
];

    $codesNL = array(
"-30" => "Volledig lichamelijk onderzoek",
"-31" => "Gericht lichamelijk onderzoek",
"-32" => "Gevoeligheidsonderzoek",
"-33" => "Microbiologisch/immunologisch onderz",
"-34" => "Bloedonderzoek",
"-35" => "Urineonderzoek",
"-36" => "Faecesonderzoek",
"-37" => "Histologie/cytologie",
"-38" => "Ander laboratoriumonderzoek nao",
"-39" => "Functieonderzoek",
"-40" => "Diagnostische endoscopie",
"-41" => "Röntgen/beeldvormend onderzoek",
"-42" => "Elektrische afleidingen",
"-43" => "Ander diagnostisch onderzoek",
"-44" => "Immunisatie/preventieve medicatie",
"-45" => "Gezondheidsvoorlichting/advies/dieet",
"-46" => "Overleg binnen eerste lijn",
"-47" => "Overleg met specialist",
"-48" => "Verhelderen/gesprek over vraag patiënt",
"-49" => "Andere preventieve verrichting",
"-50" => "Medicatie-recept/verzoek/injectie",
"-51" => "Incisie/drainage/spoelen/aspiratie",
"-52" => "Excisie/biopsie/cauterisatie",
"-53" => "Instrumentatie/catheterisatie/dilat",
"-54" => "Hechting/gipsspalk/prothese",
"-55" => "Locale injectie/infiltratie",
"-56" => "Verband/compressie/tamponade",
"-57" => "Fysiotherapie/revalidatie",
"-58" => "Therapeutisch gesprek/counselen",
"-59" => "Andere therapeutische verrichting",
"-60" => "Uitslag onderzoek/verrichting",
"-61" => "Uitslag onderz/verricht and hulpverl",
"-62" => "Administratieve verrichting",
"-63" => "Follow-up contact niet gespecificeerd",
"-64" => "Episode/contact op initiatief hulpverl",
"-65" => "Episode/contact op initiatief derde",
"-66" => "Verwijzing andere eerstelijns hulpverl",
"-67" => "Verwijzing naar specialist/ziekenhuis",
"-68" => "Andere verwijzing nao",
"-69" => "Andere reden voor contact nao",
"A01" => "Gegen pijn/pijn meerdere plaatsen",
"A02" => "Koude rillingen",
"A03" => "Koorts",
"A04" => "Algemene moeheid/zwakte",
"A05" => "Zich ziek voelen",
"A06" => "Flauwvallen/syncope",
"A07" => "Coma",
"A08" => "Zwelling",
"A09" => "Zweetprobleem",
"A10" => "Bloeding nao",
"A11" => "Pijn op de borst nao",
"A13" => "Bezorgd over/angstig voor behandeling",
"A16" => "Prikkelbare zuigeling",
"A18" => "Ontevreden/bezorgd over uiterlijk",
"A20" => "Verzoek om/gesprek over euthanasie",
"A21" => "Risicofactor voor kanker",
"A23" => "Risicofactor nao",
"A25" => "Angst voor de dood/het sterven",
"A26" => "Angst voor kanker nao",
"A27" => "Angst voor andere ziekte nao",
"A28" => "Functiebeperking/handicap nao",
"A29" => "Andere algemene symptomen/klachten",
"A70" => "Tuberculose",
"A71" => "Mazelen",
"A72" => "Waterpokken",
"A73" => "Malaria",
"A74" => "Rode hond",
"A75" => "Mononucleosis infectiosa",
"A76" => "Andere virusziekte met exantheem",
"A77" => "Andere virusziekte nao",
"A78" => "Andere infectieziekte nao",
"A79" => "Maligniteit nao",
"A80" => "Trauma/letsel nao",
"A81" => "Multitrauma/multipele letsels",
"A82" => "Laat gevolg van trauma",
"A84" => "Geneesmiddelintoxicatie",
"A85" => "Geneesmiddelbijwerking",
"A86" => "Toxisch effect niet-medicinale stof",
"A87" => "Complicatie medische behandeling",
"A88" => "Schadelijk gevolg fysische factor",
"A89" => "Gevolg prothese",
"A90" => "Aangeboren afwijkingen multipele/nao",
"A91" => "Abnormale uitslag onderzoek nao",
"A92" => "Allergie/allergische reactie nao",
"A93" => "Premature pasgeborene",
"A94" => "Andere perinatale morbiditeit",
"A95" => "Perinatale mortaliteit",
"A96" => "Dood",
"A97" => "Geen ziekte",
"A98" => "Preventie",
"A99" => "Ziekte/toestand niet gespec aard/lok",
"B02" => "Vergrote/pijnlijke lymfeklier(en)",
"B04" => "Symptomen/klachten bloed",
"B25" => "Angst voor AIDS/HIV",
"B26" => "Angst voor kanker bloed/lymfe",
"B27" => "Angst voor andere ziekte bloed/lymfe",
"B28" => "Functiebeperking/handicap (B)",
"B29" => "And sympt/klacht lymfe/immuun-syst.",
"B70" => "Acute lymphadenitis",
"B71" => "Chronische/niet gespec lymphadenitis",
"B72" => "Z.van Hodgkin/non-Hodgkin lymfoom",
"B73" => "Leukemie",
"B74" => "Andere maligniteit bloed/lymfestelsel",
"B75" => "Benigne/niet gespec neopl bloed/lymfe",
"B76" => "Traumatische miltruptuur",
"B77" => "Ander letsel bloed/lymfestelsel/milt",
"B78" => "Erfelijke hemolytische anemie",
"B79" => "Andere aangeb afwijking bloed/lymfe",
"B80" => "IJzergebrekanemie",
"B81" => "Pernicieuze/foliumzuurdeﬁ c anemie",
"B82" => "Andere/niet gespeciﬁ ceerde anemie",
"B83" => "Purpura/stollingsstoornis",
"B84" => "Abnormale leukocyten",
"B87" => "Splenomegalie",
"B90" => "HIV-infectie/AIDS",
"B99" => "Andere ziekte bloed/lymfe/milt/immuun",
"D01" => "Gegeneraliseerde buikpijn/buikkrampen",
"D02" => "Maagpijn",
"D03" => "Zuurbranden",
"D04" => "Pijn anus/rectum",
"D05" => "Perianale jeuk",
"D06" => "Andere gelokaliseerde buikpijn",
"D07" => "Indigestie/dyspepsie",
"D08" => "Flatulentie/meteorisme/boeren",
"D09" => "Misselijkheid",
"D10" => "Braken",
"D11" => "Diarree",
"D12" => "Obstipatie",
"D13" => "Geelzucht",
"D14" => "Haematemesis",
"D15" => "Melaena",
"D16" => "Rectaal bloedverlies",
"D17" => "Incontinentie voor ontlasting",
"D18" => "Verandering faeces/defecatiepatroon",
"D19" => "Symptomen/klachten tanden/tandvlees",
"D20" => "Symptomen/klachten mond/tong/lippen",
"D21" => "Slikprobleem",
"D23" => "Hepatomegalie",
"D24" => "Zwelling in buik nao",
"D25" => "Opgezette buik",
"D26" => "Angst voor kanker spijsvert",
"D27" => "Angst voor andere ziekte spijsvert",
"D28" => "Functiebeperking/handicap (D)",
"D29" => "Andere symptomen/klachten spijsvert",
"D70" => "Gastrointestinale infectie",
"D71" => "Bof",
"D72" => "Virushepatitis",
"D73" => "Verondersteld inf gastro-enteritis",
"D74" => "Maligniteit maag",
"D75" => "Maligniteit colon/rectum",
"D76" => "Maligniteit pancreas",
"D77" => "Andere maligniteit spijsvert nao",
"D78" => "Benigne/niet gespec neopl spijsvert",
"D79" => "Corpus alienum spijsverteringsorganen",
"D80" => "Ander letsel spijsverteringsorganen",
"D81" => "Aangeboren afwijking spijsvert",
"D82" => "Ziekte tanden/tandvlees",
"D83" => "Ziekte mond/tong/lippen",
"D84" => "Ziekte oesophagus",
"D85" => "Ulcus duodeni",
"D86" => "Ander peptisch ulcus",
"D87" => "Stoornis maagfunctie",
"D88" => "Appendicitis",
"D89" => "Hernia inguinalis",
"D90" => "Hiatus hernia",
"D91" => "Andere hernia abdominalis",
"D92" => "Diverticulose/diverticulitis",
"D93" => "Irritable bowel syndrome",
"D94" => "Chronische enteritis/colitis ulcerosa",
"D95" => "Anusﬁ ssuur/perianaal abces",
"D96" => "Wormen/andere parasieten",
"D97" => "Leverziekte nao",
"D98" => "Cholecystitis/cholelithiasis",
"D99" => "Andere ziekte spijsverteringsorganen",
"F01" => "Pijn oog",
"F02" => "Rood oog",
"F03" => "Afscheiding uit oog",
"F04" => "Vlekken/vliegjes voor de ogen",
"F05" => "Andere visusstoornis",
"F13" => "Abnormaal gevoel aan oog",
"F14" => "Abnormale oogbewegingen",
"F15" => "Abnormaal uiterlijk oog",
"F16" => "Symptomen/klachten ooglid",
"F17" => "Symptomen/klachten door bril",
"F18" => "Symptomen/klachten door contactlens",
"F27" => "Angst voor oogziekte",
"F28" => "Functiebeperking/handicap (F)",
"F29" => "Andere symptomen/klachten oog",
"F70" => "Infectieuze conjunctivitis",
"F71" => "Allergische conjunctivitis",
"F72" => "Blepharitis/hordeolum/chalazion",
"F73" => "Andere infectie/ontsteking oog",
"F74" => "Neoplasma oog/adnexen",
"F75" => "Contusie/bloeding oog",
"F76" => "Corpus alienum in oog",
"F79" => "Ander letsel oog",
"F80" => "Stenose ductus lacrimalis zuigeling",
"F81" => "Andere aangeboren afwijking oog",
"F82" => "Ablatio retinae",
"F83" => "Retinopathie",
"F84" => "Maculadegeneratie",
"F85" => "Ulcus corneae",
"F86" => "Trachoom",
"F91" => "Refractie-afwijking",
"F92" => "Cataract",
"F93" => "Glaucoom",
"F94" => "Blindheid",
"F95" => "Strabisme",
"F99" => "Andere ziekte oog/oogadnexen",
"H01" => "Oorpijn",
"H02" => "Symptomen/klachten gehoor",
"H03" => "Oorsuizen",
"H04" => "Afscheiding in/uit oor",
"H05" => "Bloed in/uit oor",
"H13" => "Verstopt gevoel oor",
"H15" => "Ontevreden/bezorgd over uiterlijk oor",
"H27" => "Angst voor oorziekte",
"H28" => "Functiebeperking/handicap (H)",
"H29" => "Andere symptomen/klachten oor",
"H70" => "Otitis externa",
"H71" => "Otitis media acuta/myringitis",
"H72" => "Otitis media met effusie",
"H73" => "Tubair catarre/tubastenose",
"H74" => "Chronische otitis media",
"H75" => "Neoplasma oor",
"H76" => "Corpus alienum in oor",
"H77" => "Perforatie trommelvlies",
"H78" => "Oppervlakkig letsel oor",
"H79" => "Ander letsel oor",
"H80" => "Aangeboren afwijking oor",
"H81" => "Overmatig cerumen",
"H82" => "Vertigineus syndroom",
"H83" => "Otosclerose",
"H84" => "Presbyacusis",
"H85" => "Akoestisch trauma",
"H86" => "Doofheid",
"H99" => "Andere ziekte oor/mastoid",
"K01" => "Pijn toegeschreven aan hart",
"K02" => "Druk/beklemming toegeschr. aan hart",
"K03" => "Pijn cardiovasculair stelsel nao",
"K04" => "Hartkloppingen/bewust van hartslag",
"K05" => "Andere onregelmatige hartslag",
"K06" => "Opgezette aderen",
"K07" => "Gezwollen enkels/enkeloedeem",
"K22" => "Risicofactor voor cardiovasc ziekte",
"K24" => "Angst voor hartziekte",
"K25" => "Angst voor hoge bloeddruk",
"K27" => "Angst voor and cardiovasc ziekte",
"K28" => "Functiebeperking/handicap (K)",
"K29" => "Andere sympt/klacht cardiovasc stelsel",
"K70" => "Infectieziekte cardiovasculair stelsel",
"K71" => "Acuut reuma/reumatische hartziekte",
"K72" => "Neoplasma cardiovasculair stelsel",
"K73" => "Aangeb afwijking cardiovasc stelsel",
"K74" => "Ischemische hartziekte met angina",
"K75" => "Acuut myocardinfarct",
"K76" => "Ischemische hartziekte zonder angina",
"K77" => "Decompensatio cordis",
"K78" => "Boezemﬁ brilleren/-fladderen",
"K79" => "Paroxysmale tachycardie",
"K80" => "Hartritmestoornis nao",
"K81" => "Hartgeruis/vaatgeruis nao",
"K82" => "Pulmonale hartziekte",
"K83" => "Hartklepziekte nao",
"K84" => "Andere hartziekte",
"K85" => "Verhoogde bloeddruk",
"K86" => "Hypertensie zonder orgaanbeschadig.",
"K87" => "Hypertensie met orgaanbeschadiging",
"K88" => "Orthostatische hypotensie",
"K89" => "Voorbijgaande cerebrale ischemie",
"K90" => "Cerebrovasculair accident (CVA)",
"K91" => "Cerebrovasculaire ziekte",
"K92" => "Atherosclerose/ziekte perif arteriën",
"K93" => "Longembolie",
"K94" => "Phlebitis/thrombophlebitis",
"K95" => "Varices been",
"K96" => "Hemorroïden",
"K99" => "Andere ziekte cardiovasculair stelsel ",
"L01" => "Symptomen/klachten nek",
"L02" => "Symptomen/klachten rug",
"L03" => "Symptomen/klachten lage-rug",
"L04" => "Symptomen/klachten borstkas",
"L05" => "Symptomen/klachten flank/oksel",
"L07" => "Symptomen/klachten kaak",
"L08" => "Symptomen/klachten schouder",
"L09" => "Symptomen/klachten arm",
"L10" => "Symptomen/klachten elleboog",
"L11" => "Symptomen/klachten pols",
"L12" => "Symptomen/klachten hand/vinger",
"L13" => "Symptomen/klachten heup",
"L14" => "Symptomen/klachten been/dijbeen",
"L15" => "Symptomen/klachten knie",
"L16" => "Symptomen/klachten enkel",
"L17" => "Symptomen/klachten voet/teen",
"L18" => "Spierpijn",
"L19" => "Symptomen/klachten spier nao",
"L20" => "Symptomen/klachten gewricht nao",
"L26" => "Angst voor kanker bewegingsst.",
"L27" => "Angst voor andere ziekte bewegingsst.",
"L28" => "Functiebeperking/handicap (L)",
"L29" => "And symptomen/klachten bewegingsst.",
"L70" => "Infectieziekte bewegingsst.",
"L71" => "Maligniteit bewegingsst.",
"L72" => "Fractuur radius/ulna",
"L73" => "Fractuur tibia/ﬁ bula",
"L74" => "Fractuur hand/voet",
"L75" => "Fractuur femur",
"L76" => "Andere fractuur",
"L77" => "Verstuiking/distorsie enkel",
"L78" => "Verstuiking/distorsie knie",
"L79" => "Verstuiking/distorsie gewricht nao",
"L80" => "Luxatie/subluxatie",
"L81" => "Ander letsel bewegingsst.",
"L82" => "Aangeboren afwijking bewegingsst.",
"L83" => "Neksyndroom",
"L84" => "Rugsyndroom zonder uitstralende pijn",
"L85" => "Verworven afwijking wervelkolom",
"L86" => "Rugsyndroom met uitstralende pijn",
"L87" => "Bursitis/tendinitis/synoviitis nao",
"L88" => "Reumatoïde arthritis",
"L89" => "Coxartrose",
"L90" => "Gonartrose",
"L91" => "Andere perifere artrose",
"L92" => "Schoudersyndroom",
"L93" => "Epicondylitis lateralis",
"L94" => "Osteochondrose",
"L95" => "Osteoporose",
"L96" => "Acuut inwendig knieletsel",
"L97" => "Benigne/niet gespec neopl bewegingsst",
"L98" => "Verworven afwijking extremiteiten",
"L99" => "Andere ziekte bewegingsapparaat",
"N01" => "Hoofdpijn",
"N03" => "Aangezichtspijn",
"N04" => "Restless legs",
"N05" => "Tintelen vingers/voeten/tenen",
"N06" => "Andere sensibiliteitsstoornis",
"N07" => "Convulsie/stuip",
"N08" => "Abnormale onwillekeurige bewegingen",
"N16" => "Stoornis reuk/smaak",
"N17" => "Vertigo/duizeligheid",
"N18" => "Verlamming/krachtsverlies",
"N19" => "Spraakstoornis",
"N26" => "Angst voor kanker zenuwstelsel",
"N27" => "Angst voor andere ziekte zenuwstelsel",
"N28" => "Functiebeperking/handicap (N)",
"N29" => "Andere sympt./klachten zenuwstelsel",
"N70" => "Poliomyelitis",
"N71" => "Meningitis/encephalitis",
"N72" => "Tetanus",
"N73" => "Andere infectieziekte zenuwstelsel",
"N74" => "Maligniteit zenuwstelsel",
"N75" => "Benigne neoplasma zenuwstelsel",
"N76" => "Niet gespec neoplasma zenuwstelsel",
"N79" => "Commotio cerebri",
"N80" => "Ander letsel hoofd",
"N81" => "Ander letsel zenuwstelsel",
"N85" => "Aangeboren afwijking zenuwstelsel",
"N86" => "Multiple sclerose",
"N87" => "Parkinsonisme",
"N88" => "Epilepsie",
"N89" => "Migraine",
"N90" => "Clusterhoofdpijn",
"N91" => "Facialisparalyse/Bell’s palsy",
"N92" => "Trigeminusneuralgie",
"N93" => "Carpale tunnelsyndroom",
"N94" => "Perifere neuritis/neuropathie",
"N95" => "Spanningshoofdpijn",
"N99" => "Andere ziekte zenuwstelsel",
"P01" => "Angstig/nerveus/gespannen gevoel",
"P02" => "Acute stressreactie",
"P03" => "Depressief gevoel",
"P04" => "Prikkelbaar/boos gevoel/gedrag",
"P05" => "Zich oud voelen/gedragen",
"P06" => "Slaapstoornis",
"P07" => "Verminderd seksueel verlangen",
"P08" => "Verminderde seksuele bevrediging",
"P09" => "Bezorgdheid over seksuele voorkeur",
"P10" => "Stamelen/stotteren/tic",
"P11" => "Eetprobleem bij kind",
"P12" => "Enuresis",
"P13" => "Encopresis/problemen toilettraining",
"P15" => "Chronisch alcoholmisbruik",
"P16" => "Acuut alcoholmisbruik",
"P17" => "Tabaksmisbruik",
"P18" => "Geneesmiddelmisbruik",
"P19" => "Drugsmisbruik",
"P20" => "Geheugenstoornis",
"P22" => "Gedragsprobleem kind",
"P23" => "Gedragsprobleem adolescent",
"P24" => "Speciﬁ ek leerprobleem",
"P25" => "Levensfaseprobleem volwassene",
"P27" => "Angst voor psychische ziekte",
"P28" => "Functiebeperking/handicap (P)",
"P29" => "Andere psychische sympt./klachten",
"P70" => "Dementie",
"P71" => "Andere organische psychose",
"P72" => "Schizofrenie",
"P73" => "Affectieve psychose",
"P74" => "Angststoornis/angsttoestand",
"P75" => "Somatisatiestoornis",
"P76" => "Depressieve stoornis",
"P77" => "Suïcide/suïcidepoging",
"P78" => "Neurasthenie/surmenage",
"P79" => "Fobie/dwangstoornis",
"P80" => "Persoonlijkheidsstoornis",
"P81" => "Hyperkinetische stoornis",
"P82" => "Posttraumatische stressstoornis",
"P85" => "Mentale retardatie",
"P86" => "Anorexia nervosa/boulimie",
"P98" => "Psychose nao",
"P99" => "Andere psychische ziekte",
"R01" => "Pijn toegeschreven aan luchtwegen",
"R02" => "Kortademigheid",
"R03" => "Piepende ademhaling",
"R04" => "Ander probleem ademhaling",
"R05" => "Hoesten",
"R06" => "Epistaxis/neusbloeding",
"R07" => "Niezen/neusverstopping",
"R08" => "Andere symptomen/klachten neus",
"R09" => "Symptomen/klachten neusbijholten nao",
"R21" => "Symptomen/klachten keel",
"R23" => "Symptomen/klachten stem",
"R24" => "Haemoptoe",
"R25" => "Abnormaal sputum/slijm",
"R26" => "Angst voor kanker luchtwegen",
"R27" => "Angst voor andere ziekte luchtwegen",
"R28" => "Functiebeperking/handicap (R)",
"R29" => "Andere sympt./klachten lucht-wegen",
"R71" => "Kinkhoest",
"R72" => "Streptokokken angina",
"R73" => "Furunkel/abces neus",
"R74" => "Acute infectie bovenste luchtwegen",
"R75" => "Acute/chronische sinusitis",
"R76" => "Acute tonsillitis",
"R77" => "Acute laryngitis/tracheitis",
"R78" => "Acute bronchitis/bronchiolitis",
"R79" => "Chronische bronchitis",
"R80" => "Influenza",
"R81" => "Pneumonie",
"R82" => "Pleuritis/pleuravocht",
"R83" => "Andere infectie luchtwegen",
"R84" => "Maligniteit bronchus/long",
"R85" => "Andere maligniteit luchtwegen",
"R86" => "Benigne neoplasma luchtwegen",
"R87" => "Corpus alienum neus/larynx/bronchus",
"R88" => "Ander letsel luchtwegen",
"R89" => "Aangeboren afwijking luchtwegen",
"R90" => "Hypertroﬁ e tonsillen/adenoïd",
"R92" => "Niet gespec neoplasma luchtwegen",
"R95" => "Chronisch obstructieve longziekte",
"R96" => "Astma",
"R97" => "Allergische rhinitis",
"R98" => "Hyperventilatiesyndroom",
"R99" => "Andere ziekte luchtwegen",
"S01" => "Pijn/gevoeligheid huid",
"S02" => "Jeuk",
"S03" => "Wratten",
"S04" => "Lokale zwelling/knobbel huid",
"S05" => "Mult zwellingen/knobbels huid",
"S06" => "Lokaal exantheem",
"S07" => "Gegeneraliseerd exantheem",
"S08" => "Verandering in kleur huid",
"S09" => "Infectie vinger/teen",
"S10" => "Furunkel/karbunkel",
"S11" => "Posttraumatische huidinfectie",
"S12" => "Beet/steek insect",
"S13" => "Beet mens/dier",
"S14" => "Brandwond",
"S15" => "Corpus alienum in huid",
"S16" => "Buil/kneuzing",
"S17" => "Schaafwond/schram/blaar ",
"S18" => "Scheurwond/snijwond",
"S19" => "Ander huidletsel",
"S20" => "Likdoorn/eeltknobbel",
"S21" => "Symptomen/klachten aspect huid",
"S22" => "Symptomen/klachten nagels",
"S23" => "Haaruitval/kaalheid",
"S24" => "Symptomen/klachten haar/hoofdhuid",
"S26" => "Angst voor kanker huid",
"S27" => "Angst voor andere ziekte huid",
"S28" => "Functiebeperking/handicap (S)",
"S29" => "Andere symptomen/klachten huid",
"S70" => "Herpes zoster",
"S71" => "Herpes simplex",
"S72" => "Scabies/andere ziekte door mijten",
"S73" => "Pediculosis/andere huidinfestatie",
"S74" => "Dermatomycose",
"S75" => "Candidiasis huid",
"S76" => "Andere huidinfectie",
"S77" => "Maligniteit huid",
"S78" => "Lipoom",
"S79" => "Benigne/niet gespec neoplasma huid",
"S80" => "Fotokeratose/zonnebrand",
"S81" => "Hemangioom/lymfangioom",
"S82" => "Naevus",
"S83" => "Andere aangeboren afwijking huid",
"S84" => "Impetigo",
"S85" => "Pilonidaal cyste/ﬁ stel",
"S86" => "Seborroisch eczeem",
"S87" => "Constitutioneel eczeem",
"S88" => "Contacteczeem",
"S89" => "Luieruitslag",
"S90" => "Pityriasis rosea",
"S91" => "Psoriasis",
"S92" => "Ziekte zweetklieren",
"S93" => "Atheroomcyste",
"S94" => "Unguis incarnatus",
"S95" => "Molluscum contagiosum",
"S96" => "Acne",
"S97" => "Chronisch huidulcus",
"S98" => "Urticaria",
"S99" => "Andere ziekte huid",
"T01" => "Overmatige dorst",
"T02" => "Overmatige eetlust",
"T03" => "Verminderde eetlust",
"T04" => "Voedingsprobleem zuigeling/kind",
"T05" => "Voedingsprobleem volwassene",
"T07" => "Gewichtstoename",
"T08" => "Gewichtsverlies",
"T10" => "Vertraagde groei",
"T11" => "Dehydratie",
"T26" => "Angst voor kanker endocriene klieren",
"T27" => "Angst and ziekte endocr/stofwisseling",
"T28" => "Functiebeperking/handicap (T)",
"T29" => "And sympt/klacht endocr/stofwis/voed",
"T70" => "Infectie endocriene klier",
"T71" => "Maligniteit schildklier",
"T72" => "Benigne neoplasma schildklier",
"T73" => "And/niet gespec neopl endocriene klier",
"T78" => "Ductus thyreoglossus/cyste",
"T80" => "And aangeb afwijking endocr/stofwis",
"T81" => "Struma",
"T82" => "Adipositas",
"T83" => "Overgewicht",
"T85" => "Hyperthyreoïdie/thyreotoxicose",
"T86" => "Hypothyreoïdie/myxoedeem",
"T87" => "Hypoglykemie",
"T89" => "Insuline afhankelijke diabetes",
"T90" => "Niet insuline afhankelijke diabetes",
"T91" => "Vitamine-/voedingsdeﬁ ciëntie",
"T92" => "Jicht",
"T93" => "Vetstofwisselingsstoornis",
"T99" => "Andere ziekte endocr/stofwis/voeding",
"U01" => "Pijnlijke mictie",
"U02" => "Frequente mictie/aandrang",
"U04" => "Urine-incontinentie",
"U05" => "Ander mictieprobleem",
"U06" => "Hematurie",
"U07" => "Andere symptomen/klachten urine",
"U08" => "Urineretentie",
"U13" => "Andere symptomen/klachten blaas",
"U14" => "Symptomen/klachten nier",
"U26" => "Angst voor kanker urinewegen",
"U27" => "Angst voor andere ziekte urinewegen",
"U28" => "Functiebeperking/handicap (U)",
"U29" => "Andere sympt./klachten urine-wegen",
"U70" => "Pyelonephritis/pyelitis",
"U71" => "Cystitis/andere urineweginfectie",
"U72" => "Urethritis",
"U75" => "Maligniteit nier",
"U76" => "Maligniteit blaas",
"U77" => "Andere maligniteit urinewegen",
"U78" => "Benigne neoplasma urinewegen",
"U79" => "Niet gespec neoplasma urinewegen",
"U80" => "Letsel urinewegen",
"U85" => "Aangeboren afwijking urinewegen",
"U88" => "Glomerulonephritis/nefrose",
"U90" => "Orthostatische proteïnurie/albuminurie",
"U95" => "Urolithiasis",
"U98" => "Abnormale uitslag urine-onderzoek nao",
"U99" => "Andere ziekte urinewegen",
"W01" => "Vraag bestaan zwangerschap",
"W02" => "Angst zwanger te zijn",
"W03" => "Bloedverlies tijdens zwangerschap",
"W05" => "Braken/misselijkheid tijdens zwang",
"W10" => "Postcoitum anticonceptie",
"W11" => "Orale anticonceptie",
"W12" => "Intra-uteriene anticonceptie",
"W13" => "Sterilisatie vrouw",
"W14" => "Andere vorm van anticonceptie vrouw",
"W15" => "Infertiliteit/subfertiliteit vrouw",
"W17" => "Post-partum bloedverlies",
"W18" => "Andere sympt./klachten post-partum",
"W19" => "Sympt./klachten borst/borstvoeding",
"W21" => "Ontevreden/bezorgd uiterlijk zwang",
"W27" => "Angst voor complicatie zwangerschap",
"W28" => "Functiebeperking/handicap (W)",
"W29" => "Andere sympt./klachten zwanger-schap",
"W70" => "Puerperale infectie/sepsis",
"W71" => "Zwangerschapcomplicerende infectie",
"W72" => "Maligniteit gerelateerd aan zwang",
"W73" => "Benigne/niet gespec neopl zwangersch.",
"W75" => "Zwangerschapcomplicerend letsel",
"W76" => "Zwang compl aangeboren afw moeder",
"W78" => "Zwangerschap",
"W79" => "Ongewenste zwangerschap",
"W80" => "Ectopische zwangerschap",
"W81" => "Zwangerschapstoxicose",
"W82" => "Spontane abortus",
"W83" => "Abortus provocatus",
"W84" => "Zwangerschap met verhoogd risico",
"W85" => "Zwangerschapsdiabetes",
"W90" => "Ongecompl bevalling levendgeborene",
"W91" => "Ongecompl bevalling doodgeborene",
"W92" => "Gecompl bevalling levendgeborene",
"W93" => "Gecompliceerde bevall. doodgeborene",
"W94" => "Mastitis puerperalis",
"W95" => "Andere ziekte borsten zwang/kraambed",
"W96" => "Andere complicatie kraambed",
"W99" => "Andere ziekte zwangerschap/bevalling",
"X01" => "Pijn geslachtsorganen vrouw",
"X02" => "Menstruatiepijn",
"X03" => "Intermenstruele pijn",
"X04" => "Pijnlijke coitus vrouw",
"X05" => "Amenorroe/oligomenorroe",
"X06" => "Menorragie",
"X07" => "Onregelmatige/frequente menstruatie",
"X08" => "Intermenstrueel bloedverlies",
"X09" => "Premenstruele symptomen/klachten",
"X10" => "Uitstel van de menstruatie",
"X11" => "Menopauzale symptomen/klachten",
"X12" => "Postmenopauzaal bloedverlies",
"X13" => "Bloedverlies na coitus",
"X14" => "Vaginale afscheiding",
"X15" => "Andere vaginale symptomen/klachten",
"X16" => "Symptomen/klachten vulva",
"X17" => "Symptomen/klachten kleine bekken vr",
"X18" => "Pijn in de borst(en) vrouw",
"X19" => "Knobbel/zwelling borst vrouw",
"X20" => "Symptomen/klachten tepel vrouw",
"X21" => "Andere symptomen/klachten borsten vr",
"X22" => "Ontevreden over uiterlijk borsten vr",
"X23" => "Angst voor seks overdraagbare aand vr",
"X24" => "Angst voor seksueel disfunctioneren vr",
"X25" => "Angst voor kanker geslachtsorganen vr",
"X26" => "Angst voor borstkanker vrouw",
"X27" => "Angst voor and ziekte geslachtsorg vr",
"X28" => "Functiebeperking/handicap (X)",
"X29" => "And sympt./klachten geslachtsorg vr",
"X70" => "Syphilis vrouw",
"X71" => "Gonorroe vrouw",
"X72" => "Genitale candidiasis vrouw",
"X73" => "Genitale trichomoniasis vrouw",
"X74" => "Ontsteking kleine bekken/PID",
"X75" => "Maligniteit cervix uteri",
"X76" => "Maligniteit borst vrouw",
"X77" => "Andere maligniteit geslachtsorganen vr",
"X78" => "Fibromyoom uterus",
"X79" => "Benigne neoplasma borst vrouw",
"X80" => "Benigne neoplasma geslachtsorg vr",
"X81" => "And/niet gespec neopl geslachtsorg vr",
"X82" => "Letsel geslachtsorganen vrouw",
"X83" => "Aangeb afwijking geslachtsorganen vr",
"X84" => "Vaginitis/vulvitis nao",
"X85" => "Ziekte cervix uteri nao",
"X86" => "Abnormale cervixuitstrijk",
"X87" => "Prolaps vagina/uterus",
"X88" => "Mastopathie/cyste borst vrouw",
"X89" => "Premenstrueel spanningssyndroom",
"X90" => "Herpes genitalis vrouw",
"X91" => "Condylomata acuminata vrouw",
"X92" => "Chlamydia-infectie geslachtsorganen vr",
"X99" => "And ziekte geslachtsorganen/borsten vr",
"Y01" => "Pijn penis",
"Y02" => "Pijn testis/scrotum",
"Y03" => "Afscheiding urethra man",
"Y04" => "Andere symptomen/klachten penis",
"Y05" => "Andere sympt/klacht scrotum/testis",
"Y06" => "Symptomen/klachten prostaat",
"Y07" => "Impotentie nao",
"Y08" => "Sympt/klacht seks functie nao man",
"Y10" => "Sub-/infertiliteit man",
"Y13" => "Sterilisatie man",
"Y14" => "Andere vorm van geboorteregeling man",
"Y16" => "Symptomen/klachten borst(en) man",
"Y24" => "Angst voor seks disfunctioneren man",
"Y25" => "Angst voor seks.overdraagb.aand man",
"Y26" => "Angst voor kanker geslachtsorg. man",
"Y27" => "Angst voor and.ziekte gesl.org. man",
"Y28" => "Functiebeperking/handicap (Y)",
"Y29" => "And sympt/klachten geslachtsorg man",
"Y70" => "Syphilis man",
"Y71" => "Gonorroe man",
"Y72" => "Herpes genitalis man",
"Y73" => "Prostatitis/vesiculitis seminalis",
"Y74" => "Orchitis/epididymitis",
"Y75" => "Balanitis",
"Y76" => "Condylomata acuminata man",
"Y77" => "Maligniteit prostaat",
"Y78" => "And maligniteit geslachtsorganen man",
"Y79" => "Ben/niet gespec.neopl.gesl.org.man",
"Y80" => "Letsel geslachtsorganen man",
"Y81" => "Phimosis/slurfpreputium",
"Y82" => "Hypospadie",
"Y83" => "Niet ingedaalde testis",
"Y84" => "And. aangeboren afw geslachtsorg man",
"Y85" => "Benigne prostaathypertroﬁ e",
"Y86" => "Hydrocele",
"Y99" => "Andere ziekte geslachtsorganen man",
"Z01" => "Armoede/ﬁ nancieel probleem",
"Z02" => "Probleem met voedsel/water",
"Z03" => "Probleem met huisvesting/buurt",
"Z04" => "Sociaal-cultureel probleem",
"Z05" => "Probleem met werk",
"Z06" => "Probleem met werkloosheid",
"Z07" => "Probleem met opleiding",
"Z08" => "Probleem met sociale zekerheid",
"Z09" => "Juridisch probleem",
"Z10" => "Probleem met gezondheidszorg",
"Z11" => "Probleem ziek zijn/acceptatie ziekte",
"Z12" => "Relatieprobleem met partner",
"Z13" => "Probleem met gedrag van partner",
"Z14" => "Probleem met ziekte van partner",
"Z15" => "Verlies/overlijden van partner",
"Z16" => "Relatieprobleem met kind",
"Z18" => "Probleem met ziekte van kind",
"Z19" => "Verlies/overlijden van kind",
"Z20" => "Relatieprobleem met ouders/familie",
"Z21" => "Probleem met gedrag ouders/familie",
"Z22" => "Probleem met ziekte ouders/familie",
"Z23" => "Verlies/overlijden van ouders/familie",
"Z24" => "Relatieprobleem met vrienden",
"Z25" => "Aanranding/and schadel. gebeurtenis",
"Z27" => "Angst een sociaal probleem te hebben",
"Z28" => "Functiebeperking/handicap (Z)",
"Z29" => "Sociaal probleem nao",
);

        foreach ($codesFR as $c) {
            $code = $c[1];
            $chapter = $chapters[$code[0]];
            $component = $components[$c[0]];
            $nameFR = $c[2];
            $nameNL = $codesNL[$code];

            $output->writeln($code.' - '.$nameFR.' - '.$nameNL);

            $e = (new Code())
                ->setCode($code)
                ->setChapter($chapter)
                ->setComponent($component)
                ->setName(array("fr" => $nameFR, "nl" => $nameNL));

            $em->persist($e);
        }
    }
}