<?php

/*
 * Chill is a software for social workers 
 *
 * Copyright (C) 2014, Champs Libres Cooperative SCRLFS, <http://www.champs-libres.coop>
 * 
 * This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

namespace Chill\ICPC2Bundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Chill\ICPC2Bundle\Entity\Code;

/**
 * Load Code into database
 */
class LoadCode extends AbstractFixture implements OrderedFixtureInterface
{
    public function getOrder()
    {
        return 17003;
    }
    
    public function load(ObjectManager $manager)
    {
        echo "loading Code...\n";

$codes = [
["pro","-30","Ex médical/bilan santé détaillé"],
["pro","-31","Ex médical/bilan santé partiel"],
["pro","-32","Test de sensibilité"],
["pro","-33","Ex microbiologique/immunologique"],
["pro","-34","Autre analyse de sang"],
["pro","-35","Autre analyse d'urine"],
["pro","-36","Autre analyse de selles"],
["pro","-37","Cytologie/histologie"],
["pro","-38","Autre analyse de laboratoire"],
["pro","-39","Epreuve fonctionnelle"],
["pro","-40","Endoscopie"],
["pro","-41","Radiologie diagnostique/imagerie"],
["pro","-42","Tracé électrique"],
["pro","-43","Autre procédure diagnostique"],
["pro","-44","Vaccination/médication préventive"],
["pro","-45","Recom./éducation santé/avis/régime"],
["pro","-46","Discussion entre dispensateurs SSP"],
["pro","-47","Discussion dispensateur spécialiste"],
["pro","-48","Clarification de la demande du patient"],
["pro","-49","Autre procédure préventive"],
["pro","-50","Médication/prescription/injection"],
["pro","-51","Incision/drainage/aspiration"],
["pro","-52","Excision/biopsie/cautér/débridation"],
["pro","-53","Perfusion/intubat./dilatat./appareillage"],
["pro","-54","Répar/fixation/suture/plâtre/prothèse"],
["pro","-55","Traitement local/infiltration"],
["pro","-56","Pansement/compression/bandage"],
["pro","-57","Thérapie manuelle/médecine physique"],
["pro","-58","Conseil thérap/écoute/examens"],
["pro","-59","Autres procédures thérapeutiques"],
["pro","-60","Résultats analyses/examens"],
["pro","-61","Résultats ex/procéd autre dispensateur"],
["pro","-62","Contact administratif"],
["pro","-63","Rencontre de suivi"],
["pro","-64","Epis. nouveau/en cours init. par disp."],
["pro","-65","Epis. nouveau/en cours init. par tiers"],
["pro","-66","Référence à dispens. SSP non médecin"],
["pro","-67","Référence à médecin"],
["pro","-68","Autre référence"],
["pro","-69","Autres procédures"],
["sym","A01","Douleur générale/de sites multiples"],
["sym","A02","Frissons"],
["sym","A03","Fièvre"],
["sym","A04","Fatigue/faiblesse générale"],
["sym","A05","Sensation d'être malade"],
["sym","A06","Evanouissement/syncope"],
["sym","A07","Coma"],
["sym","A08","Gonflement"],
["sym","A09","P. de transpiration"],
["sym","A10","Saignement/hémorragie NCA"],
["sym","A11","Douleur thoracique NCA"],
["sym","A13","Préoc. par/peur traitement médical"],
["sym","A16","Nourrisson irritable"],
["sym","A18","Préoc. par son aspect extérieur"],
["sym","A20","Demande/discussion sur l'euthanasie"],
["sym","A21","Facteur de risque de cancer"],
["sym","A23","Facteur de risque NCA"],
["sym","A25","Peur de la mort, de mourir"],
["sym","A26","Peur du cancer NCA"],
["sym","A27","Peur d'une autre maladie NCA"],
["sym","A28","Limitation de la fonction/incap. NCA"],
["sym","A29","Autre S/P général"],
["inf","A70","Tuberculose"],
["inf","A71","Rougeole"],
["inf","A72","Varicelle"],
["inf","A73","Paludisme"],
["inf","A74","Rubéole"],
["inf","A75","Mononucléose infectieuse"],
["inf","A76","Autre exanthème viral"],
["inf","A77","autre maladie virale NCA"],
["inf","A78","Autre maladie infectieuse NCA"],
["neo","A79","Cancer NCA"],
["inj","A80","Traumatisme/lésion traumat. NCA"],
["inj","A81","Polytraumatisme/lésions multiples"],
["inj","A82","Effet tardif d'un traumatisme"],
["inj","A84","Intoxication par subst. médicinale"],
["inj","A85","Effet sec. subst. médicinale"],
["inj","A86","Effet toxique subst. non médicinale"],
["inj","A87","Complication de traitement médical"],
["inj","A88","Effet sec. de facteur physique"],
["inj","A89","Effet sec. de matériel prothétique"],
["con","A90","Anom. congénitale NCA/multiple"],
["oth","A91","Résultat d'investigat. anormale NCA"],
["oth","A92","Allergie/réaction allergique NCA"],
["oth","A93","Nouveau-né prématuré"],
["oth","A94","Autre morbidité périnatale"],
["oth","A95","Mortalité périnatale"],
["oth","A96","Mort"],
["oth","A97","Pas de maladie"],
["oth","A98","Gestion santé/médecine préventive"],
["oth","A99","Maladie de nature/site non précisé"],
["sym","B02","Ganglion lymph. augmenté/ douloureux"],
["sym","B04","S/P du sang"],
["sym","B25","Peur du SIDA/du VIH"],
["sym","B26","Peur du cancer du sang/lymph."],
["sym","B27","Peur autre maladie sang/lymph/rate"],
["sym","B28","Limitation de la fonction/incap. (B)"],
["sym","B29","Autre S/P du syst. lymph./immunol."],
["inf","B70","Adénite aiguë"],
["inf","B71","Adénite chronique/non-spécifique"],
["neo","B72","Maladie de Hodgkin/lymphome"],
["neo","B73","Leucémie"],
["neo","B74","Autre cancer du sang"],
["neo","B75","Tumeur bénigne/indét. sang/lymph."],
["inj","B76","Rupture traumat. de la rate"],
["inj","B77","Autre traumat. sang/lymph/rate"],
["con","B78","Anémie hémolytique héréditaire"],
["con","B79","Autre anom. congénitale sang/ lymph/rate"],
["oth","B80","Anémie par déficience en fer"],
["oth","B81","Anémie carence vit B12/ac. folique"],
["oth","B82","Autre anémie/indét."],
["oth","B83","Purpura/défaut de coagulation"],
["oth","B84","Globules blancs anormaux"],
["oth","B87","Splénomégalie"],
["oth","B90","Infection par le virus HIV, SIDA"],
["oth","B99","Autre maladie sang/lymph/rate"],
["sym","D01","Douleur/crampes abdominales gén."],
["sym","D02","Douleur abdominale/épigastrique"],
["sym","D03","Brûlure/brûlant/brûlement estomac"],
["sym","D04","Douleur rectale/anale"],
["sym","D05","Démangeaisons périanales"],
["sym","D06","Autre douleur abdominale loc."],
["sym","D07","Dyspepsie/indigestion"],
["sym","D08","Flatulence/gaz/renvoi"],
["sym","D09","Nausée"],
["sym","D10","Vomissement"],
["sym","D11","Diarrhée"],
["sym","D12","Constipation"],
["sym","D13","Jaunisse"],
["sym","D14","Hématémèse/vomissement de sang"],
["sym","D15","Méléna"],
["sym","D16","Saignement rectal"],
["sym","D17","Incontinence rectale"],
["sym","D18","Modification selles/mouvem. intestin"],
["sym","D19","S/P dents/gencives"],
["sym","D20","S/P bouche/langue/lèvres"],
["sym","D21","P. de déglutition"],
["sym","D23","Hépatomégalie"],
["sym","D24","Masse abdominale NCA"],
["sym","D25","Distension abdominale"],
["sym","D26","Peur du cancer du syst. digestif"],
["sym","D27","Peur d’une autre maladie digestive"],
["sym","D28","Limitation de la fonction/incap. (D)"],
["sym","D29","Autre S/P du syst. digestif"],
["inf","D70","Infection gastro-intestinale"],
["inf","D71","Oreillons"],
["inf","D72","Hépatite virale"],
["inf","D73","Gastro-entérite présumée infectieuse"],
["neo","D74","Cancer de l'estomac"],
["neo","D75","Cancer du colon/du rectum"],
["neo","D76","Cancer du pancréas"],
["neo","D77","Autre cancer digestif/NCA"],
["neo","D78","Tumeur bénigne/indét. du syst. dig."],
["inj","D79","CE du syst. digestif"],
["inj","D80","Autre traumat. du syst. digestif"],
["con","D81","Anom. congénitale du syst. digestif"],
["oth","D82","Maladie des dents/des gencives"],
["oth","D83","Maladie bouche/langue/lèvres"],
["oth","D84","Maladie de l’œsophage"],
["oth","D85","Ulcère duodénal"],
["oth","D86","Autre ulcère peptique"],
["oth","D87","Trouble de la fonction gastrique"],
["oth","D88","Appendicite"],
["oth","D89","Hernie inguinale"],
["oth","D90","Hernie hiatale"],
["oth","D91","Autre hernie abdominale"],
["oth","D92","Maladie diverticulaire"],
["oth","D93","Syndrome du colon irritable"],
["oth","D94","Entérite chronique/colite ulcéreuse"],
["oth","D95","Fissure anale/abcès périanal"],
["oth","D96","Vers/autre parasite"],
["oth","D97","Maladie du foie NCA"],
["oth","D98","Cholécystite/cholélithiase"],
["oth","D99","Autre maladie du syst. Digestif"],
["sym","F01","Oeil douloureux"],
["sym","F02","Oeil rouge"],
["sym","F03","Ecoulement de l’œil"],
["sym","F04","Taches visuelles/flottantes"],
["sym","F05","Autre perturbation de la vision"],
["sym","F13","Sensation oculaire anormale"],
["sym","F14","Mouvements oculaires anormaux"],
["sym","F15","Apparence anormale de l’œil"],
["sym","F16","S/P de la paupière"],
["sym","F17","S/P lunettes"],
["sym","F18","S/P lentilles de contact"],
["sym","F27","Peur d’une maladie de l’œil"],
["sym","F28","Limitation de la fonction/incap. (F)"],
["sym","F29","Autre S/P de l’œil"],
["inf","F70","Conjonctivite infectieuse"],
["inf","F71","Conjonctivite allergique"],
["inf","F72","Blépharite, orgelet, chalazion"],
["inf","F73","Autre infection/inflammation de l’œil"],
["neo","F74","Tumeur de l’œil et des annexes"],
["inj","F75","Contusion/hémorragie de l’œil"],
["inj","F76","CE dans l’œil"],
["inj","F79","Autre lésion traumat. de l’œil"],
["con","F80","Sténose canal lacrymal de l'enfant"],
["con","F81","Autre anom. congénitale de l’œil"],
["oth","F82","Décollement de la retire"],
["oth","F83","Rétinopathie"],
["oth","F84","Dégénérescence maculaire"],
["oth","F85","Ulcère de la cornée"],
["oth","F86","Trachome"],
["oth","F91","Défaut de réfraction"],
["oth","F92","Cataracte"],
["oth","F93","Glaucome"],
["oth","F94","Cécité"],
["oth","F95","Strabisme"],
["oth","F99","Autre maladie de l’œil/annexes"],
["sym","H01","Douleur d'oreille/otalgie"],
["sym","H02","P. d'audition"],
["sym","H03","Acouphène/bourdonnement d'oreille"],
["sym","H04","Ecoulement de l'oreille"],
["sym","H05","Saignement de l'oreille"],
["sym","H13","Sensation d'oreille bouchée"],
["sym","H15","Préoc. par l'aspect des oreilles"],
["sym","H27","Peur d’une maladie de l'oreille"],
["sym","H28","Limitation de la fonction/incap. (H)"],
["sym","H29","Autre S/P de l' oreille"],
["inf","H70","Otite externe"],
["inf","H71","Otite moyenne aiguë/myringite"],
["inf","H72","Otite moyenne séreuse"],
["inf","H73","Salpingite d'eustache"],
["inf","H74","Otite moyenne chronique"],
["neo","H75","Tumeur de l'oreille"],
["inj","H76","CE dans l'oreille"],
["inj","H77","Perforation du tympan"],
["inj","H78","Lésion traumat. superf. de l'oreille"],
["inj","H79","Autre lésion traumat. de l'oreille"],
["con","H80","Anom. congénitale de l'oreille"],
["oth","H81","Excès de cérumen"],
["oth","H82","Syndrome vertigineux"],
["oth","H83","Otosclérose"],
["oth","H84","Presbyacousie"],
["oth","H85","Traumatisme sonore"],
["oth","H86","Surdité"],
["oth","H99","Autre maladie de l'oreille/ mastoïde"],
["sym","K01","Douleur cardiaque"],
["sym","K02","Oppression/constriction cardiaque"],
["sym","K03","Douleur cardiovasculaire NCA"],
["sym","K04","Palpitat./perception battements card."],
["sym","K05","Autre battement cardiaque irrégulier"],
["sym","K06","Veines proéminentes"],
["sym","K07","Oedème, gonflement des chevilles"],
["sym","K22","Facteur risque mal. cardio-vasculaire"],
["sym","K24","Peur d’une maladie de cœur"],
["sym","K25","Peur d' de l'hypertension"],
["sym","K27","Peur autre maladie cardio-vasculaire"],
["sym","K28","Limitation de la fonction/incap. (K)"],
["sym","K29","Autre S/P cardiovasculaire"],
["inf","K70","Infection du syst. cardio-vasculaire"],
["inf","K71","RAA/maladie cardiaque rhumatismale"],
["neo","K72","Tumeur cardio-vasculaire"],
["con","K73","Anom. congénitale cardio-vasculaire"],
["oth","K74","Cardiopathie ischémique avec angor"],
["oth","K75","Infarctus myocardique aigu"],
["oth","K76","Cardiopathie ischémique sans angor"],
["oth","K77","Décompensation cardiaque"],
["oth","K78","Fibrillation auriculaire/flutter"],
["oth","K79","Tachycardie paroxystique"],
["oth","K80","Arythmie cardiaque NCA"],
["oth","K81","Souffle cardiaque/artériel NCA"],
["oth","K82","Cœur pulmonaire"],
["oth","K83","Valvulopathie NCA"],
["oth","K84","Autre maladie cardiaque"],
["oth","K85","Pression sanguine élevée"],
["oth","K86","Hypertension non compliquée"],
["oth","K87","Hypertension avec complication"],
["oth","K88","Hypotension orthostatique"],
["oth","K89","Ischémie cérébrale transitoire"],
["oth","K90","Accident vasculaire cérébral"],
["oth","K91","Maladie cérébrovasculaire"],
["oth","K92","Athéroscl./mal. vasculaire périphér."],
["oth","K93","Embolie pulmonaire"],
["oth","K94","Phlébite et thrombophlébite"],
["oth","K95","Varices des jambes"],
["oth","K96","Hémorroïdes"],
["oth","K99","Autre maladie cardio-vasculaire"],
["sym","L01","S/P du cou"],
["sym","L02","S/P du dos"],
["sym","L03","S/P des lombes"],
["sym","L04","S/P du thorax"],
["sym","L05","S/P du flanc et du creux axillaire"],
["sym","L06","S/P de la mâchoire"],
["sym","L07","S/P de l'épaule"],
["sym","L08","S/P du bras"],
["sym","L09","S/P du coude"],
["sym","L11","S/P du poignet"],
["sym","L12","S/P de la main et du doigt"],
["sym","L13","S/P de la hanche"],
["sym","L14","S/P de la jambe et de la cuisse"],
["sym","L15","S/P du genou"],
["sym","L16","S/P de la cheville"],
["sym","L17","S/P du pied et de l'orteil"],
["sym","L18","Douleur musculaire"],
["sym","L19","S/P musculaire NCA"],
["sym","L20","S/P d'une articulation NCA"],
["sym","L26","Peur cancer syst. ostéo-articulaire"],
["sym","L27","Peur autre maladie syst. ostéo-articul."],
["sym","L28","Limitation de la fonction/incap. (L)"],
["sym","L29","Autre S/P ostéo-articulaire"],
["inf","L70","Infection du syst. ostéo-articulaire"],
["neo","L71","Cancer du syst. ostéo-articulaire"],
["inj","L72","Fracture du radius/du cubitus"],
["inj","L73","Fracture du tibia/du péroné"],
["inj","L74","Fracture de la main/du pied"],
["inj","L75","Fracture du fémur"],
["inj","L76","Autre fracture"],
["inj","L77","Entorse de la cheville"],
["inj","L78","Entorse du genou"],
["inj","L79","Entorse articulaire NCA"],
["inj","L80","Luxation et subluxation"],
["inj","L81","Lésion traumat. NCA ostéo-articulaire"],
["con","L82","Anom. congénitale ostéo-articulaire"],
["oth","L83","Syndrome cervical"],
["oth","L84","Syndr. dorso-lomb. sans irradiation"],
["oth","L85","Déformation acquise de la colonne"],
["oth","L86","Syndr. dorso-lombaire et irradiation"],
["oth","L87","Bursite, tendinite, synovite NCA"],
["oth","L88","Polyarthrite rhumatoïde séropositive"],
["oth","L89","Coxarthrose"],
["oth","L90","Gonarthrose"],
["oth","L91","Autre arthrose"],
["oth","L92","Syndrome de l'épaule"],
["oth","L93","Coude du joueur de tennis"],
["oth","L94","Ostéochondrose"],
["oth","L95","Ostéoporose"],
["inj","L96","Lésion aiguë interne du genou"],
["neo","L97","Autre tumeur bén./indét. ostéo-artic."],
["oth","L98","Déformation acquise membres inf."],
["oth","L99","Autre maladie ostéo-articulaire"],
["sym","N01","Mal de tête"],
["sym","N03","Douleur de la face"],
["sym","N04","Jambes sans repos"],
["sym","N05","Fourmillements doigts, pieds, orteils"],
["sym","N06","Autre perturbation de la sensibilité"],
["sym","N07","Convulsion/crise comitiale"],
["sym","N08","Mouvements involontaires anormaux"],
["sym","N16","Perturbation du goût/de l'odorat"],
["sym","N17","Vertige/étourdissement"],
["sym","N18","Paralysie/faiblesse"],
["sym","N19","Trouble de la parole"],
["sym","N26","Peur d'un cancer neurologique"],
["sym","N27","Peur d’une autre maladie neurologique"],
["sym","N28","Limitation de la fonction/incap. (N)"],
["sym","N29","Autre S/P neurologique"],
["inf","N70","Poliomyélite"],
["inf","N71","Méningite/encéphalite NCA"],
["inf","N72","Tétanos"],
["inf","N73","Autre infection neurologique"],
["neo","N74","Cancer du syst. neurologique"],
["neo","N75","Tumeur bénigne neurologique"],
["neo","N76","Autre tumeur indét. neurologique"],
["inj","N79","Commotion"],
["inj","N80","Autre lésion traumat. de la tête"],
["inj","N81","Autre lésion traumat. neurologique"],
["con","N85","Anom. congénitale neurologique"],
["oth","N86","Sclérose en plaque"],
["oth","N87","Syndrome parkinsonien"],
["oth","N88","Epilepsie"],
["oth","N89","Migraine"],
["oth","N90","Algie vasculaire de la face"],
["oth","N91","Paralysie faciale/paralysie de Bell"],
["oth","N92","Névralgie du trijumeau"],
["oth","N93","Syndrome du canal carpien"],
["oth","N94","Névrite/neuropathie périphérique"],
["oth","N95","Céphalée de tension"],
["oth","N99","Autre maladie neurologique"],
["sym","P01","Sensation anxiété/nervosité/tension"],
["sym","P02","Réaction de stress aiguë"],
["sym","P03","Sensation de dépression"],
["sym","P04","Sentiment/comport. irritable/colère"],
["sym","P05","Sensation vieux, comportement sénile"],
["sym","P06","Perturbation du sommeil"],
["sym","P07","Diminution du désir sexuel"],
["sym","P08","Diminution accomplissement sexuel"],
["sym","P09","Préoccupation sur identité sexuelle"],
["sym","P10","Bégaiement, bredouillement, tic"],
["sym","P11","Trouble de l'alimentation de l'enfant"],
["sym","P12","Enurésie"],
["sym","P13","Encoprésie"],
["sym","P15","Alcoolisme chronique"],
["sym","P16","Alcoolisation aiguë"],
["sym","P17","Usage abusif du tabac"],
["sym","P18","Usage abusif de médicament"],
["sym","P19","Usage abusif de drogue"],
["sym","P20","Perturbation de la mémoire"],
["sym","P22","S/P du comportement de l'enfant"],
["sym","P23","S/P du comportement de l'adolescent"],
["sym","P24","P. spécifique de l'apprentissage"],
["sym","P25","Problèmes de phase de vie adulte"],
["sym","P27","Peur d'un trouble mental"],
["sym","P28","Limitation de la fonction/incap. (P)"],
["sym","P29","Autre S/P psychologique"],
["oth","P70","Démence"],
["oth","P71","Autre psychose organique"],
["oth","P72","Schizophrénie"],
["oth","P73","Psychose affective"],
["oth","P74","Trouble anxieux/état anxieux"],
["oth","P75","Trouble somatoforme"],
["oth","P76","Dépression"],
["oth","P77","Suicide/tentative de suicide"],
["oth","P78","Neurasthénie, surmenage"],
["oth","P79","Phobie, trouble obsessionnel compulsif"],
["oth","P80","Trouble de la personnalité"],
["oth","P81","Trouble hyperkinétique"],
["oth","P82","Syndrome de stress post-traumatique"],
["oth","P85","Retard mental"],
["oth","P86","Anorexie mentale, boulimie"],
["oth","P98","Autre psychose NCA"],
["oth","P99","Autre trouble psychologique"],
["sym","R01","Douleur du syst. respiratoire"],
["sym","R02","Souffle court, dyspnée"],
["sym","R03","Sibilance"],
["sym","R04","Autre P. respiratoire"],
["sym","R05","Toux"],
["sym","R06","Saignement de nez, épistaxis"],
["sym","R07","Congestion nasale, éternuement"],
["sym","R08","Autre S/P du nez"],
["sym","R09","S/P des sinus"],
["sym","R21","S/P de la gorge"],
["sym","R23","S/P de la voix"],
["sym","R24","Hémoptysie"],
["sym","R25","Expectoration/glaire anormale"],
["sym","R26","Peur d'un cancer du syst. respiratoire"],
["sym","R27","Peur d’une autre maladie respiratoire"],
["sym","R28","Limitation de la fonction/incap. ( R)"],
["sym","R29","Autre S/P respiratoire"],
["inf","R71","Coqueluche"],
["inf","R72","Streptococcie pharyngée"],
["inf","R73","Furoncle/abcès du nez"],
["inf","R74","Infection aiguë voies respiratoire sup."],
["inf","R75","Sinusite aiguë/chronique"],
["inf","R76","Angine aiguë"],
["inf","R77","Laryngite, trachéite aiguë"],
["inf","R78","Bronchite aiguë, bronchiolite"],
["inf","R79","Bronchite chronique"],
["inf","R80","Grippe"],
["inf","R81","Pneumonie"],
["inf","R82","Pleurésie, épanchement pleural"],
["inf","R83","Autre infection respiratoire"],
["neo","R84","Cancer des bronches, du poumon"],
["neo","R85","Autre cancer respiratoire"],
["neo","R86","Tumeur respiratoire bénigne"],
["inj","R87","CE du nez, du larynx, des bronches"],
["inj","R88","Autre lésion traumat. du syst. resp."],
["con","R89","Anom. congénitale du syst. resp."],
["oth","R90","Hypertrophie amygdales/végétations"],
["neo","R92","Autre tumeur indét. du syst. resp."],
["oth","R95","Mal. pulmonaire chronique obstructive"],
["oth","R96","Asthme"],
["oth","R97","Rhinite allergique"],
["oth","R98","Syndrome d'hyperventilation"],
["oth","R99","Autre maladie respiratoire"],
["sym","S01","Douleur/hypersensibilité de la peau"],
["sym","S02","Prurit"],
["inf","S03","Verrue"],
["sym","S04","Tuméfaction/gonflement loc. peau"],
["sym","S05","Tuméfactions/gonflements gén. peau"],
["sym","S06","Eruption localisée"],
["sym","S07","Eruption généralisée"],
["sym","S08","Modification de la couleur de la peau"],
["inf","S09","Doigt/orteil infecté"],
["inf","S10","Furoncle/anthrax"],
["inf","S11","Infection post-traumat. de la peau"],
["inj","S12","Piqûre d'insecte"],
["inj","S13","Morsure animale/humaine"],
["inj","S14","Brûlure cutanée"],
["inj","S15","CE dans la peau"],
["inj","S16","Ecchymose/contusion"],
["inj","S17","Eraflure, égratignure, ampoule"],
["inj","S18","Coupure/lacération"],
["inj","S19","Autre lésion traumat. de la peau"],
["sym","S20","Cor/callosité"],
["sym","S21","S/P au sujet de la texture de la peau"],
["sym","S22","S/P de l'ongle"],
["sym","S23","Calvitie/perte de cheveux"],
["sym","S24","Autre S/P cheveux, poils/cuir chevelu"],
["sym","S26","Peur du cancer de la peau"],
["sym","S27","Peur d’une autre maladie de la peau"],
["sym","S28","Limitation de la fonction/incap. (S)"],
["sym","S29","Autre S/P de la peau"],
["inf","S70","Zona"],
["inf","S71","Herpes simplex"],
["inf","S72","Gale/autre acariose"],
["inf","S73","Pédiculose/autre infestation peau"],
["inf","S74","Dermatophytose"],
["inf","S75","Moniliase/candidose de la peau"],
["inf","S76","Autre maladie infectieuse de la peau"],
["neo","S77","Cancer de la peau"],
["neo","S78","Lipome"],
["neo","S79","Autre tumeur bén./indét. de la peau"],
["neo","S80","Kératose actinique/coup de soleil"],
["con","S81","Hémangiome/lymphangiome"],
["con","S82","Naevus/naevus pigmentaire"],
["con","S83","Autre anom. congénitale de la peau"],
["inf","S84","Impétigo"],
["oth","S85","Kyste/fistule pilonidal"],
["oth","S86","Dermatite séborrhéique"],
["oth","S87","Dermatite atopique/eczéma"],
["oth","S88","Dermatite et allergie de contact"],
["oth","S89","Erythème fessier"],
["oth","S90","Pytiriasis rosé"],
["oth","S91","Psoriasis"],
["oth","S92","Maladie des glandes sudoripares"],
["oth","S93","Kyste sébacé"],
["oth","S94","Ongle incarné"],
["inf","S95","Molluscum contagiosum"],
["oth","S96","Acné"],
["oth","S97","Ulcère chronique de la peau"],
["oth","S98","Urticaire"],
["oth","S99","Autre maladie de la peau"],
["sym","T01","Soif excessive"],
["sym","T02","Appétit excessif"],
["sym","T03","Perte d'appétit"],
["sym","T04","P. d'alimentation nourrisson/enfant"],
["sym","T05","P. d'alimentation de l'adulte"],
["sym","T07","Gain de poids"],
["sym","T08","Perte de poids"],
["sym","T10","Retard de croissance"],
["sym","T11","Déshydratation"],
["sym","T26","Peur d'un cancer du syst. endocrinien"],
["sym","T27","Peur autre mal. endoc/métab./nutrit."],
["sym","T28","Limitation de la fonction/incap. (T)"],
["sym","T29","Autre S/P endoc/métab./nutrit.,"],
["inf","T70","Infection du syst. endocrinien"],
["neo","T71","Cancer de la thyroïde"],
["neo","T72","Tumeur bénigne de la thyroïde"],
["neo","T73","Tumeur indét. du syst. endocrinien"],
["con","T78","Canal/kyste thyréoglosse"],
["con","T80","Anom. congénit. endoc/ métab./nutrit."],
["oth","T81","Goitre"],
["oth","T82","Obésité"],
["oth","T83","Excès pondéral"],
["oth","T85","Hyperthyroïdie/thyréotoxicose"],
["oth","T86","Hypothyroïdie/myxœdème"],
["oth","T87","Hypoglycémie"],
["oth","T89","Diabète insulino-dépendant"],
["oth","T90","Diabète non insulino-dépendant"],
["oth","T91","Carence vitaminique/nutritionnelle"],
["oth","T92","Goutte"],
["oth","T93","Trouble du métabolisme des lipides"],
["oth","T99","Autre maladie endoc/métab./nutrit"],
["sym","U01","Dysurie/miction douloureuse"],
["sym","U02","Miction fréquente/impérieuse"],
["sym","U04","Incontinence urinaire"],
["sym","U05","Autre P. de miction"],
["sym","U06","Hématurie"],
["sym","U07","Autre S/P au sujet de l'urine"],
["sym","U08","Rétention d'urine"],
["sym","U13","Autre S/P de la vessie"],
["sym","U14","S/P du rein"],
["sym","U26","Peur d'un cancer du syst. urinaire"],
["sym","U27","Peur d’une autre maladie urinaire"],
["sym","U28","Limitation de la fonction/incap. (U)"],
["sym","U29","Autre S/P urinaire"],
["inf","U70","Pyélonéphrite/pyélite"],
["inf","U71","Cystite/autre infection urinaire"],
["inf","U72","Urétrite"],
["neo","U75","Cancer du rein"],
["neo","U76","Cancer de la vessie"],
["neo","U77","Autre cancer urinaire"],
["neo","U78","Tumeur bénigne du tractus urinaire"],
["neo","U79","Autre tumeur indét. urinaire"],
["inj","U80","Lésion traumat. du tractus urinaire"],
["con","U85","Anom. congénitale du tractus urinaire"],
["oth","U88","Glomérulonéph./syndr. néphrotique"],
["oth","U90","Protéinurie orthostatique"],
["oth","U95","Lithiase urinaire"],
["oth","U98","Analyse urinaire anormale NCA"],
["oth","U99","Autre maladie urinaire"],
["sym","W01","Question de grossesse"],
["sym","W02","Peur d'être enceinte"],
["sym","W03","Saignement pendant la grossesse"],
["sym","W05","Nausée/vomissement de grossesse"],
["sym","W10","Contraception post-coïtale"],
["sym","W11","Contraception orale"],
["sym","W12","Contraception intra-utérine"],
["sym","W13","Stérilisation chez la femme"],
["sym","W14","Autre contraception chez la femme"],
["sym","W15","Stérilité - hypofertilité de la femme"],
["sym","W17","Saignement du post-partum"],
["sym","W18","Autre S/P du post-partum"],
["sym","W19","S/P du sein/lactation post-partum"],
["sym","W21","Préoc. par modific. image et grossesse"],
["sym","W27","Peur complications de la grossesse"],
["sym","W28","Limitation de la fonction/incap. (W)"],
["sym","W29","Autre S/P de la grossesse"],
["inf","W70","Infection puerpérale, sepsis"],
["inf","W71","Infection compliquant la grossesse"],
["neo","W72","Tumeur maligne avec grossesse"],
["neo","W73","Tumeur bénigne/indét. et grossesse"],
["inj","W75","Lésion traumat. et grossesse"],
["con","W76","Anom. congénitale et grossesse"],
["oth","W78","Grossesse"],
["oth","W79","Grossesse non désirée"],
["oth","W80","Grossesse ectopique"],
["oth","W81","Toxémie gravidique"],
["oth","W82","Avortement spontané"],
["oth","W83","Avortement provoque"],
["oth","W84","Grossesse a haut risque"],
["oth","W85","Diabète gravidique"],
["oth","W90","Acc. non complique, enfant vivant"],
["oth","W91","Acc. non complique, enfant mort"],
["oth","W92","Acc. complique, enfant vivant"],
["oth","W93","Acc. complique, enfant mort"],
["oth","W94","Mastite puerpérale"],
["oth","W95","Autre mal. sein et grossesse/lactation"],
["oth","W96","Autre complication puerpérale"],
["oth","W99","Autre maladie de la grossesse/acc."],
["sym","X01","Douleur génitale chez la femme"],
["sym","X02","Douleur menstruelle"],
["sym","X03","Douleur intermenstruelle"],
["sym","X04","Rapport sexuel douloureux femme"],
["sym","X05","Menstruation absente/rare"],
["sym","X06","Menstruation excessive"],
["sym","X07","Menstruation irrégulière/fréquente"],
["sym","X08","Saignement intermenstruel"],
["sym","X09","S/P prémenstruel"],
["sym","X10","Ajournement des menstruations"],
["sym","X11","S/P liés a la ménopause"],
["sym","X12","Saignement de la post-ménopause"],
["sym","X13","Saignement post-coïtal femme"],
["sym","X14","Ecoulement vaginal"],
["sym","X15","S/P du vagin"],
["sym","X16","S/P de la vulve"],
["sym","X17","S/P du petit bassin chez la femme"],
["sym","X18","Douleur du sein chez la femme"],
["sym","X19","Tuméfaction/masse du sein femme"],
["sym","X20","S/P du mamelon chez la femme"],
["sym","X21","Autre S/P du sein chez la femme"],
["sym","X22","Préoc. par l'apparence des seins"],
["sym","X23","Peur d'une MST chez la femme"],
["sym","X24","Peur dysfonction sexuelle femme"],
["sym","X25","Peur d'un cancer génital femme"],
["sym","X26","Peur d'un cancer du sein femme"],
["sym","X27","Peur autre mal. génitale/sein femme"],
["sym","X28","Limitation de la fonction/incap. (X)"],
["sym","X29","Autre S/P génital chez la femme"],
["inf","X70","Syphilis chez la femme"],
["inf","X71","Gonococcie chez la femme"],
["inf","X72","Candidose génitale chez la femme"],
["inf","X73","Trichomonase génitale femme"],
["inf","X74","Mal. inflammatoire pelvienne femme"],
["neo","X75","Cancer du col de l'utérus"],
["neo","X76","Cancer du sein chez la femme"],
["neo","X77","Autre cancer génital chez la femme"],
["neo","X78","Fibrome utérin"],
["neo","X79","Tumeur bénigne du sein femme"],
["neo","X80","Tumeur bénigne génitale femme"],
["neo","X81","Autre tumeur génitale indét. femme"],
["inj","X82","Lésion traumat. génitale femme"],
["con","X83","Anom. génitale congénitale femme"],
["oth","X84","Vaginite/vulvite NCA"],
["oth","X85","Maladie du col de l'utérus NCA"],
["oth","X86","Frottis de col anormal"],
["oth","X87","Prolapsus utero-vaginal"],
["oth","X88","Maladie fibrokystique du sein"],
["oth","X89","Syndrome de tension prémenstruelle"],
["inf","X90","Herpes génital chez la femme"],
["inf","X91","Condylome acuminé chez la femme"],
["inf","X92","Infection génitale  chlamydia femme"],
["oth","X99","Autre maladie génitale de la femme"],
["sym","Y01","Douleur du pénis"],
["sym","Y02","Douleur des testicules, du scrotum"],
["sym","Y03","Ecoulement urétral chez l'homme"],
["sym","Y04","Autre S/P du pénis"],
["sym","Y05","Autre S/P des testicules/du scrotum"],
["sym","Y06","S/P de la prostate"],
["sym","Y07","Impuissance sexuelle NCA"],
["sym","Y08","Autre S/P fonction sexuelle homme"],
["sym","Y10","Stérilité, hypofertilité de l'homme"],
["sym","Y13","Stérilisation de l'homme"],
["sym","Y14","Autre PF chez l'homme"],
["sym","Y16","S/P du sein chez l'homme"],
["sym","Y24","Peur dysfonction sexuelle homme"],
["sym","Y25","Peur d’une MST chez l'homme"],
["sym","Y26","Peur d'un cancer génital homme"],
["sym","Y27","Peur autre maladie génitale homme"],
["sym","Y28","Limitation de la fonction/incap. (Y)"],
["sym","Y29","Autre S/P génitale chez l'homme"],
["inf","Y70","Syphilis chez l'homme"],
["inf","Y71","Gonococcie chez l'homme"],
["inf","Y72","Herpes génital chez l'homme"],
["inf","Y73","Prostatite/vésiculite séminale"],
["inf","Y74","Orchite/épididymite"],
["inf","Y75","Balanite"],
["inf","Y76","Condylome acuminé chez l'homme"],
["neo","Y77","Cancer de la prostate"],
["neo","Y78","Autre cancer génital chez l'homme"],
["neo","Y79","Autre tum. génit. bén./indét. homme"],
["inj","Y80","Lésion traumat. génitale homme"],
["con","Y81","Phimosis/hypertrophie du prépuce"],
["con","Y82","Hypospadias"],
["con","Y83","Ectopie testiculaire"],
["con","Y84","Autre anom. congénitale homme"],
["oth","Y85","Hypertrophie bénigne de la prostate"],
["oth","Y86","Hydrocèle"],
["oth","Y99","Autre maladie génitale chez l'homme"],
["sym","Z01","Pauvreté/P. économique"],
["sym","Z02","P. d'eau/de nourriture"],
["sym","Z03","P. d'habitat/de voisinage"],
["sym","Z04","P. socioculturel"],
["sym","Z05","P. de travail"],
["sym","Z06","P. de non emploi"],
["sym","Z07","P. d'éducation"],
["sym","Z08","P. de protection sociale"],
["sym","Z09","P. légal"],
["sym","Z10","P. relatif au syst. de soins de santé"],
["sym","Z11","P. du fait d'être malade/compliance"],
["sym","Z12","P. de relation entre partenaires"],
["sym","Z13","P. de comportement du partenaire"],
["sym","Z14","P. du à la maladie du partenaire"],
["sym","Z15","Perte/décès du partenaire"],
["sym","Z16","P. de relation avec un enfant"],
["sym","Z18","P. du à la maladie d'un enfant"],
["sym","Z19","Perte/décès d'un enfant"],
["sym","Z20","P. relation autre parent/famille"],
["sym","Z21","P. comportem. autre parent/famille"],
["sym","Z22","P. du à la mal. autre parent/famille"],
["sym","Z23","Perte/décès autre parent/famille"],
["sym","Z24","P. de relation avec un ami"],
["sym","Z25","Agression/évènement nocif NCA"],
["sym","Z27","Peur d'un P. social"],
["sym","Z28","Limitation de la fonction/incap. (Z)"],
["sym","Z29","P. social NCA"]
];

        foreach ($codes as $c) {
            echo($c[1]."\n");
            $e = (new Code())
                ->setCode($c[1])
                ->setChapter($this->getReference($c[1][0]))
                ->setComponent($this->getReference($c[0]))
                ->setName(array("en" => $c[2]));

            $manager->persist($e);
        }
        
        $manager->flush();
    }
}